// export { default as HumanMadeObject } from './HumanMadeObject'
// export { default as Actor } from './Actor'
// export { default as Event } from './Actor'
// export { default as Group } from './Actor'
// export { default as Concept } from './Concept'
// export { default as ObjectType } from './Concept'
// export { default as Place } from './Concept'
export { default as Page } from './Page'
export { default as LinguisticDocument } from './Page'
