// Generated by ts-to-zod
import { rdfsLabelSchemaExtension, UBBClassExtension, UBBRightExtension, UBBTimeSpanExtension } from 'src/ubb/zod/extension';
import { z } from "zod";
import {
  CollectionSchema, ConceptSchema, CrmE10_TransferOf_Custody, CrmE12_Production, CrmE13_Attribute_Assignment, CrmE30_Right, CrmE33_E41_Linguistic_Appellation, CrmE33_Linguistic_Object, CrmE33_Linguistic_Object2, CrmE36_Visual_Item, CrmE42_Identifier, CrmE54_Dimension, CrmE55_Type, CrmE7_Activity1, CrmE7_Activity2, CrmE80_Part_Removal, CrmE8_Acquisition, CrmE9_Move, CrmP100IDiedIn, CrmP104IIsSubjectTo, CrmP108IWasProducedBy, CrmP113IWasRemovedBy, CrmP129IIsSubjectOf, CrmP138IHasRepresentation, CrmP13IWasDestroyedBy, CrmP140IWasAttributedBy, CrmP141IWasAssignedBy, CrmP14IPerformed, CrmP16IWasUsedFor, CrmP16IWasUsedFor1,
  CrmP16IWasUsedFor2, CrmP16IWasUsedFor3,
  CrmP16IWasUsedFor4, CrmP191HadDuration, CrmP1IsIdentifiedBy, CrmP2HasType, CrmP32UsedGeneralTechnique, CrmP43HasDimension, CrmP46IsComposedOf, CrmP4HasTimeSpan, CrmP67IIsReferredToBy, CrmP76HasContactPoint, CrmP94IWasCreatedBy, CrmP94IWasCreatedBy1, CrmP94IWasCreatedBy2, CrmP94IWasCreatedBy3, CrmP94IWasCreatedBy4,
  CrmP94IWasCreatedBy5, CrmP95IWasFormedBy, CrmP98IWasBorn, CrmP99IWasDissolvedBy, CrmP9ConsistsOf, DigD1_Digital_Object, DigitalObjectSchema,
  EventSchema,
  GroupSchema, HumanMadeObjectSchema, LaDigitallyAvailableVia, LaDigitallyCarriedBy, LaDigitallyShownBy, LaDigitalService, LaEstablishes,
  LaInvalidates, LaPaidAmount, LaPayment, LaRepresentsInstanceOfType, LaRightAcquisition, LinkedArtSchema, Person,
  PlaceSchema,
  ProvenanceActivitySchema, SciO19IWasObjectEncounteredAt,
  SciS19_Encounter_Event, SciS19_Encounter_Event1, TextSchema, VisualContentSchema
} from "./../types/linked_art.d";

export const linkedArtSchema = z.literal(
  "https://linked.art/ns/v1/linked-art.json",
);

export const linkedArtWithExtensionsSchema = z.array(z.string());

export const theSubjectUriSchema = z.string();

export const generalSchema = z.string();

export const specificSchema = z.union([
  z.literal("Type"),
  z.literal("Currency"),
  z.literal("Material"),
  z.literal("Language"),
  z.literal("MeasurementUnit"),
]);

export const rdfsLabelSchema = rdfsLabelSchemaExtension

export const general1Schema = z.string();

export const specific1Schema = z.literal("Type");

export const general2Schema = z.string();

export const specific2Schema = z.literal("Name");

export const crmP190HasSymbolicContentSchema = z.string();

export const general3Schema = z.string();

export const crmE56LanguageSchema = z.object({
  id: theSubjectUriSchema,
  type: general3Schema.and(z.literal("Language")),
  _label: rdfsLabelSchema.optional(),
});

export const general4Schema = z.string();

export const specific3Schema = z.literal("LinguisticObject");

export const dcFormatSchema = z.string();

export const general5Schema = z.string();

export const specific4Schema = z.literal("DigitalObject");

export const general6Schema = z.string();

export const digD1DigitalObjectSeeSchemaDigitalHtmlSchema = z.object({
  id: theSubjectUriSchema,
  type: general5Schema.and(specific4Schema),
  _label: rdfsLabelSchema.optional(),
});

export const crmE33LinguisticObject1Schema = z.object({
  id: theSubjectUriSchema,
  type: general6Schema.and(z.literal("LinguisticObject")),
  _label: rdfsLabelSchema.optional(),
});

export const general7Schema = z.string();

export const specific5Schema = z.literal("Identifier");

export const general8Schema = z.string();

export const specific6Schema = z.literal("AttributeAssignment");

export const general9Schema = z.string();

export const specific7Schema = z.literal("Place");

export const crmE53PlaceSchema = z.object({
  id: theSubjectUriSchema,
  type: general9Schema.and(specific7Schema),
  _label: rdfsLabelSchema.optional(),
});

export const general10Schema = z.string();

export const specific8Schema = z.literal("TimeSpan");

export const crmP82ABeginOfTheBeginSchema = z.string();

export const crmP81AEndOfTheBeginSchema = z.string();

export const crmP81BBeginOfTheEndSchema = z.string();

export const crmP82BEndOfTheEndSchema = z.string();

export const general11Schema = z.string();

export const specific9Schema = z.literal("Dimension");

export const crmP90HasValueSchema = z.number();

export const crmP90AHasLowerValueLimitSchema = z.number();

export const crmP90AHasUpperValueLimitSchema = z.number();

export const general12Schema = z.string();

export const general13Schema = z.string();

export const general14Schema = z.string();

export const crmE6EventSchema = z.object({
  id: theSubjectUriSchema,
  type: general13Schema.and(z.literal("Event")),
  _label: rdfsLabelSchema.optional(),
});

export const crmE7ActivitySchema = z.object({
  id: theSubjectUriSchema,
  type: general14Schema.and(z.literal("Activity")),
  _label: rdfsLabelSchema.optional(),
});

export const general15Schema = z.string();

export const specific10Schema = z.literal("Person");

export const rdfTypeSchema = z.string();

export const specific11Schema = z.literal("Group");

export const e21PersonSchema = z.object({
  id: theSubjectUriSchema,
  type: general15Schema.and(specific10Schema),
  _label: rdfsLabelSchema.optional(),
});

export const crmE74GroupSchema = z.object({
  id: theSubjectUriSchema,
  type: rdfTypeSchema.and(specific11Schema),
  _label: rdfsLabelSchema.optional(),
});

export const rdfType1Schema = z.string();

export const specific12Schema = z.literal("HumanMadeObject");

export const rdfType2Schema = z.string();

export const crmE22HumanMadeObjectSchema = z.object({
  id: theSubjectUriSchema,
  type: rdfType1Schema.and(specific12Schema),
  _label: rdfsLabelSchema.optional(),
});

export const laSetSchema = z.object({
  id: theSubjectUriSchema,
  type: rdfType2Schema.and(z.literal("Set")),
  _label: rdfsLabelSchema.optional(),
});

export const rdfType3Schema = z.string();

export const specific13Schema = z.union([
  z.literal("HumanMadeObject"),
  z.literal("Person"),
  z.literal("Group"),
  z.literal("VisualItem"),
  z.literal("LinguisticObject"),
  z.literal("Set"),
  z.literal("Place"),
  z.literal("DigitalObject"),
  z.literal("Type"),
  z.literal("Event"),
  z.literal("Activity"),
  z.literal("Period"),
]);

export const noNameSchema = z.object({
  id: theSubjectUriSchema,
  type: rdfType3Schema.and(specific13Schema),
  _label: rdfsLabelSchema.optional(),
});

export const crmP177AssignedPropertyTypeSchema = z.string();

export const general16Schema = z.array(noNameSchema);

export const rdfType4Schema = z.string();

export const crmE55TypeOrSubclassSchema = z.object({
  id: theSubjectUriSchema,
  type: rdfType4Schema.and(
    z.union([
      z.literal("Type"),
      z.literal("Language"),
      z.literal("Material"),
      z.literal("Currency"),
      z.literal("MeasurementUnit"),
    ]),
  ),
  _label: rdfsLabelSchema.optional(),
});

export const rdfType5Schema = z.string();

export const specific15Schema = z.literal("VisualItem");

export const rdfType6Schema = z.string();

export const specific16Schema = z.literal("DigitalObject");

export const laAccessPointSchema = z.array(
  digD1DigitalObjectSeeSchemaDigitalHtmlSchema,
);

export const rdfType7Schema = z.string();

export const crmE73InformationObjectSchema = z.object({
  id: theSubjectUriSchema,
  type: rdfType7Schema.and(z.literal("InformationObject")),
  _label: rdfsLabelSchema.optional(),
});

export const laMemberOfSchema = z.array(laSetSchema);

export const rdfType8Schema = z.string();

export const specific17Schema = z.literal("LinguisticObject");

export const rdfType9Schema = z.string();

export const specific18Schema = z.literal("Creation");

export const crmP9IFormsPartOfSchema = z.union([
  crmE6EventSchema,
  crmE7ActivitySchema,
]);

export const skosBroaderSchema = z.array(crmE55TypeOrSubclassSchema);

export const rdfType10Schema = z.string();

export const specific19Schema = z.literal("DigitalObject");

export const general17Schema = z.array(noNameSchema);

export const specific20Schema = z.array(
  digD1DigitalObjectSeeSchemaDigitalHtmlSchema,
);

export const rdfType11Schema = z.string();

export const specific21Schema = z.literal("DigitalService");

export const laDigitallyCarriesSchema = z.array(crmE33LinguisticObject1Schema);

export const rdfType12Schema = z.string();

export const crmE36VisualItem1Schema = z.object({
  id: theSubjectUriSchema,
  type: rdfType12Schema.and(z.literal("VisualItem")),
  _label: rdfsLabelSchema.optional(),
});

export const rdfType13Schema = z.string();

export const specific22Schema = z.literal("Activity");

export const rdfType14Schema = z.string();

export const specific23Schema = z.union([
  z.literal("Period"),
  z.literal("Event"),
  z.literal("Activity"),
]);

export const general18Schema = z.array(noNameSchema);

export const specific24Schema = z.array(crmE7ActivitySchema);

export const crmP9IFormsPartOf1Schema = z.union([
  crmE6EventSchema,
  crmE7ActivitySchema,
]);

export const rdfType15Schema = z.string();

export const specific25Schema = z.literal("Group");

export const general19Schema = z.array(noNameSchema);

export const specific26Schema = z.array(crmE74GroupSchema);

export const crmP107IIsCurrentOrFormerMemberOfSchema =
  z.array(crmE74GroupSchema);

export const crmP74HasCurrentOrFormerResidenceSchema =
  z.array(crmE53PlaceSchema);

export const rdfType16Schema = z.string();

export const specific27Schema = z.literal("Formation");

export const crmP9IFormsPartOf2Schema = z.union([
  crmE6EventSchema,
  crmE7ActivitySchema,
]);

export const rdfType17Schema = z.string();

export const specific28Schema = z.literal("Dissolution");

export const crmP9IFormsPartOf3Schema = z.union([
  crmE6EventSchema,
  crmE7ActivitySchema,
]);

export const rdfType18Schema = z.string();

export const specific29Schema = z.literal("VisualItem");

export const general20Schema = z.array(noNameSchema);

export const specific30Schema = z.array(crmE36VisualItem1Schema);

export const rdfType19Schema = z.string();

export const specific31Schema = z.literal("Right");

export const crmP106IFormsPartOfSchema = z.array(
  z.union([crmE36VisualItem1Schema, crmE33LinguisticObject1Schema]),
);

export const crmP129IsAboutSchema = z.array(noNameSchema);

export const crmP138RepresentsSchema = z.array(noNameSchema);

export const rdfType20Schema = z.string();

export const specific32Schema = z.literal("HumanMadeObject");

export const general21Schema = z.array(noNameSchema);

export const specific33Schema = z.array(crmE22HumanMadeObjectSchema);

export const rdfType21Schema = z.string();

export const crmE57MaterialSchema = z.object({
  id: theSubjectUriSchema,
  type: rdfType21Schema.and(z.literal("Material")),
  _label: rdfsLabelSchema.optional(),
});

export const crmP52HasCurrentOwnerSchema = z.array(
  z.union([e21PersonSchema, crmE74GroupSchema]),
);

export const crmP50HasCurrentKeeperSchema = z.array(
  z.union([e21PersonSchema, crmE74GroupSchema]),
);

export const laCurrentPermanentCustodianSchema = z.array(
  z.union([e21PersonSchema, crmE74GroupSchema]),
);

export const crmP65ShowsVisualItemSchema = z.array(crmE36VisualItem1Schema);

export const crmP128CarriesSchema = z.array(crmE33LinguisticObject1Schema);

export const rdfType22Schema = z.string();

export const specific34Schema = z.literal("Production");

export const crmP9IFormsPartOf4Schema = z.union([
  crmE6EventSchema,
  crmE7ActivitySchema,
]);

export const rdfType23Schema = z.string();

export const specific35Schema = z.literal("Destruction");

export const crmP9IFormsPartOf5Schema = z.union([
  crmE6EventSchema,
  crmE7ActivitySchema,
]);

export const rdfType24Schema = z.string();

export const specific36Schema = z.literal("PartRemoval");

export const crmP9IFormsPartOf6Schema = z.union([
  crmE6EventSchema,
  crmE7ActivitySchema,
]);

export const rdfType25Schema = z.string();

export const specific37Schema = z.literal("Encounter");

export const crmP9IFormsPartOf7Schema = z.union([
  crmE6EventSchema,
  crmE7ActivitySchema,
]);

export const rdfType26Schema = z.string();

export const specific38Schema = z.literal("Person");

export const general22Schema = z.array(noNameSchema);

export const specific39Schema = z.array(e21PersonSchema);

export const rdfType27Schema = z.string();

export const specific40Schema = z.literal("Birth");

export const rdfType28Schema = z.string();

export const specific41Schema = z.literal("Death");

export const rdfType29Schema = z.string();

export const specific42Schema = z.literal("Place");

export const general23Schema = z.array(noNameSchema);

export const specific43Schema = z.array(crmE53PlaceSchema);

export const crmP168PlaceIsDefinedBySchema = z.string();

export const crmP89FallsWithinSchema = z.array(crmE53PlaceSchema);

export const rdfType30Schema = z.string();

export const specific44Schema = z.literal("Activity");

export const general24Schema = z.array(noNameSchema);

export const specific45Schema = z.array(crmE7ActivitySchema);

export const crmP9IFormsPartOf8Schema = z.union([
  crmE6EventSchema,
  crmE7ActivitySchema,
]);

export const rdfType31Schema = z.string();

export const specific46Schema = z.literal("Acquisition");

export const crmP23TransferredTitleFromSchema = z.array(
  z.union([e21PersonSchema, crmE74GroupSchema]),
);

export const crmP22TransferredTitleToSchema = z.array(
  z.union([e21PersonSchema, crmE74GroupSchema]),
);

export const crmP24TransferredTitleOfSchema = z.array(
  crmE22HumanMadeObjectSchema,
);

export const rdfType32Schema = z.string();

export const specific47Schema = z.literal("RightAcquisition");

export const rdfType33Schema = z.string();

export const specific48Schema = z.literal("TransferOfCustody");

export const crmP28CustodySurrenderedBySchema = z.array(
  z.union([e21PersonSchema, crmE74GroupSchema]),
);

export const crmP29CustodyReceivedBySchema = z.array(
  z.union([e21PersonSchema, crmE74GroupSchema]),
);

export const crmP30TransferredCustodyOfSchema = z.array(
  crmE22HumanMadeObjectSchema,
);

export const rdfType34Schema = z.string();

export const specific49Schema = z.literal("Payment");

export const laPaidFromSchema = z.array(
  z.union([e21PersonSchema, crmE74GroupSchema]),
);

export const laPaidToSchema = z.array(
  z.union([e21PersonSchema, crmE74GroupSchema]),
);

export const rdfType35Schema = z.string();

export const specific50Schema = z.literal("MonetaryAmount");

export const rdfType36Schema = z.string();

export const rdfType37Schema = z.string();

export const specific51Schema = z.literal("Encounter");

export const sciO19HasFoundObjectSchema = z.array(crmE22HumanMadeObjectSchema);

export const rdfType38Schema = z.string();

export const specific52Schema = z.literal("Move");

export const crmP25MovedSchema = z.array(crmE22HumanMadeObjectSchema);

export const rdfType39Schema = z.string();

export const specific53Schema = z.literal("Activity");

export const rdfType40Schema = z.string();

export const specific54Schema = z.literal("Set");

export const general25Schema = z.array(noNameSchema);

export const specific55Schema = z.array(laSetSchema);

export const rdfType41Schema = z.string();

export const specific56Schema = z.literal("LinguisticObject");

export const general26Schema = z.array(noNameSchema);

export const specific57Schema = z.array(crmE33LinguisticObject1Schema);

export const crmP106IFormsPartOf1Schema = z.array(
  z.union([crmE36VisualItem1Schema, crmE33LinguisticObject1Schema]),
);

export const noName1Schema = z.record(z.unknown());

export const crmP91HasUnitSchema = z.object({
  id: theSubjectUriSchema,
  type: general12Schema.and(z.literal("MeasurementUnit")),
  _label: rdfsLabelSchema.optional(),
});

export const digD1DigitalObjectSeeSchemaDigitalHtml1Schema = z.object({
  id: theSubjectUriSchema,
  type: general5Schema.and(specific4Schema),
  _label: rdfsLabelSchema.optional(),
});

export const crmE22HumanMadeObject1Schema = z.object({
  id: theSubjectUriSchema,
  type: rdfType1Schema.and(specific12Schema),
  _label: rdfsLabelSchema.optional(),
});

export const crmP55HasCurrentLocationSchema = z.object({
  id: theSubjectUriSchema,
  type: general9Schema.and(specific7Schema),
  _label: rdfsLabelSchema.optional(),
});

export const crmE22HumanMadeObject2Schema = z.object({
  id: theSubjectUriSchema,
  type: rdfType1Schema.and(specific12Schema),
  _label: rdfsLabelSchema.optional(),
});

export const crmE98CurrencySchema = z.object({
  id: theSubjectUriSchema,
  type: rdfType36Schema.and(z.literal("Currency")),
  _label: rdfsLabelSchema.optional(),
});

export const crmE53Place1Schema = z.object({
  id: theSubjectUriSchema,
  type: general9Schema.and(specific7Schema),
  _label: rdfsLabelSchema.optional(),
});

export const crmE53Place2Schema = z.object({
  id: theSubjectUriSchema,
  type: general9Schema.and(specific7Schema),
  _label: rdfsLabelSchema.optional(),
});

export const jSONLDContextSchema = z.union([
  linkedArtSchema,
  linkedArtWithExtensionsSchema,
]);

export const crmP72HasLanguageSchema = z.array(crmE56LanguageSchema);

export const crmP7TookPlaceAtSchema = z.array(crmE53PlaceSchema);

export const sciO13IIsTriggeredBySchema = z.array(
  z.union([crmE6EventSchema, crmE7ActivitySchema]),
);

export const crmP14CarriedOutBySchema = z.array(
  z.union([e21PersonSchema, crmE74GroupSchema]),
);

export const crmP16UsedSpecificObjectSchema = z.array(
  z.union([crmE22HumanMadeObjectSchema, laSetSchema]),
);

export const crmP15WasInfluencedBySchema = z.array(noNameSchema);

export const specific14Schema = z.array(crmE55TypeOrSubclassSchema);

export const dctermsConformsToSchema = z.array(crmE73InformationObjectSchema);

export const laDigitallyShowsSchema = z.array(crmE36VisualItem1Schema);

export const crmP45ConsistsOfSchema = z.array(crmE57MaterialSchema);

export const linkedArtSchemaSchema: z.ZodSchema<LinkedArtSchema> = z.lazy(() =>
  z.union([
    conceptSchemaSchema,
    digitalObjectSchemaSchema,
    eventSchemaSchema,
    groupSchemaSchema,
    visualContentSchemaSchema,
    humanMadeObjectSchemaSchema,
    personSchema,
    placeSchemaSchema,
    provenanceActivitySchemaSchema,
    collectionSchemaSchema,
    textSchemaSchema,
  ]),
);

export const conceptSchemaSchema: z.ZodSchema<ConceptSchema> = z.lazy(() =>
  z.object({
    "@context": jSONLDContextSchema,
    id: theSubjectUriSchema,
    type: generalSchema.and(specificSchema),
    _label: rdfsLabelSchema,
    classified_as: crmP2HasTypeSchema.optional(),
    identified_by: crmP1IsIdentifiedBySchema.optional(),
    referred_to_by: crmP67IIsReferredToBySchema.optional(),
    equivalent: general16Schema.and(specific14Schema).optional(),
    representation: crmP138IHasRepresentationSchema.optional(),
    member_of: laMemberOfSchema.optional(),
    subject_of: crmP129IIsSubjectOfSchema.optional(),
    attributed_by: crmP140IWasAttributedBySchema.optional(),
    created_by: crmP94IWasCreatedBySchema.optional(),
    broader: skosBroaderSchema.optional(),
  }).merge(UBBClassExtension).strict(),
);

export const digitalObjectSchemaSchema: z.ZodSchema<DigitalObjectSchema> =
  z.lazy(() =>
    z.object({
      "@context": jSONLDContextSchema,
      id: theSubjectUriSchema,
      type: rdfType10Schema.and(specific19Schema),
      _label: rdfsLabelSchema,
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      equivalent: general17Schema.and(specific20Schema).optional(),
      representation: crmP138IHasRepresentationSchema.optional(),
      member_of: laMemberOfSchema.optional(),
      subject_of: crmP129IIsSubjectOfSchema.optional(),
      attributed_by: crmP140IWasAttributedBySchema.optional(),
      dimension: crmP43HasDimensionSchema.optional(),
      part_of: digD1DigitalObjectSeeSchemaDigitalHtml1Schema.optional(),
      format: dcFormatSchema.optional(),
      conforms_to: dctermsConformsToSchema.optional(),
      access_point: laAccessPointSchema.optional(),
      digitally_available_via: laDigitallyAvailableViaSchema.optional(),
      digitally_carries: laDigitallyCarriesSchema.optional(),
      digitally_shows: laDigitallyShowsSchema.optional(),
      used_for: crmP16IWasUsedForSchema.optional(),
      created_by: crmP94IWasCreatedBy1Schema.optional(),
    }).merge(UBBClassExtension).strict(),
  );

export const eventSchemaSchema: z.ZodSchema<EventSchema> = z.lazy(() =>
  z.object({
    "@context": jSONLDContextSchema,
    id: theSubjectUriSchema,
    type: rdfType14Schema.and(specific23Schema),
    _label: rdfsLabelSchema,
    identified_by: crmP1IsIdentifiedBySchema.optional(),
    classified_as: crmP2HasTypeSchema.optional(),
    referred_to_by: crmP67IIsReferredToBySchema.optional(),
    equivalent: general18Schema.and(specific24Schema).optional(),
    representation: crmP138IHasRepresentationSchema.optional(),
    member_of: laMemberOfSchema.optional(),
    subject_of: crmP129IIsSubjectOfSchema.optional(),
    attributed_by: crmP140IWasAttributedBySchema.optional(),
    took_place_at: crmP7TookPlaceAtSchema.optional(),
    timespan: crmP4HasTimeSpanSchema.optional(),
    caused_by: sciO13IIsTriggeredBySchema.optional(),
    carried_out_by: crmP14CarriedOutBySchema.optional(),
    used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
    influenced_by: crmP15WasInfluencedBySchema.optional(),
    technique: crmP32UsedGeneralTechniqueSchema.optional(),
    part_of: crmP9IFormsPartOf1Schema.optional(),
  }).merge(UBBClassExtension).strict(),
);

export const groupSchemaSchema: z.ZodSchema<GroupSchema> = z.lazy(() =>
  z.object({
    "@context": jSONLDContextSchema,
    id: theSubjectUriSchema,
    type: rdfType15Schema.and(specific25Schema),
    _label: rdfsLabelSchema,
    identified_by: crmP1IsIdentifiedBySchema.optional(),
    classified_as: crmP2HasTypeSchema.optional(),
    referred_to_by: crmP67IIsReferredToBySchema.optional(),
    equivalent: general19Schema.and(specific26Schema).optional(),
    representation: crmP138IHasRepresentationSchema.optional(),
    member_of: crmP107IIsCurrentOrFormerMemberOfSchema.optional(),
    subject_of: crmP129IIsSubjectOfSchema.optional(),
    attributed_by: crmP140IWasAttributedBySchema.optional(),
    carried_out: crmP14IPerformedSchema.optional(),
    contact_point: crmP76HasContactPointSchema.optional(),
    residence: crmP74HasCurrentOrFormerResidenceSchema.optional(),
    formed_by: crmP95IWasFormedBySchema.optional(),
    dissolved_by: crmP99IWasDissolvedBySchema.optional(),
  }).merge(UBBClassExtension).strict(),
);

export const visualContentSchemaSchema: z.ZodSchema<VisualContentSchema> =
  z.lazy(() =>
    z.object({
      "@context": jSONLDContextSchema,
      id: theSubjectUriSchema,
      type: rdfType18Schema.and(specific29Schema),
      _label: rdfsLabelSchema,
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      equivalent: general20Schema.and(specific30Schema).optional(),
      member_of: laMemberOfSchema.optional(),
      subject_of: crmP129IIsSubjectOfSchema.optional(),
      attributed_by: crmP140IWasAttributedBySchema.optional(),
      dimension: crmP43HasDimensionSchema.optional(),
      subject_to: crmP104IIsSubjectToSchema.optional(),
      part_of: crmP106IFormsPartOfSchema.optional(),
      about: crmP129IsAboutSchema.optional(),
      created_by: crmP94IWasCreatedBy3Schema.optional(),
      represents: crmP138RepresentsSchema.optional(),
      represents_instance_of_type: laRepresentsInstanceOfTypeSchema.optional(),
      used_for: crmP16IWasUsedFor1Schema.optional(),
    }).merge(UBBClassExtension).strict(),
  );

export const humanMadeObjectSchemaSchema: z.ZodSchema<HumanMadeObjectSchema> =
  z.lazy(() =>
    z.object({
      "@context": jSONLDContextSchema,
      id: theSubjectUriSchema,
      type: rdfType20Schema.and(specific32Schema),
      _label: rdfsLabelSchema,
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      equivalent: general21Schema.and(specific33Schema).optional(),
      representation: crmP138IHasRepresentationSchema.optional(),
      member_of: laMemberOfSchema.optional(),
      subject_of: crmP129IIsSubjectOfSchema.optional(),
      attributed_by: crmP140IWasAttributedBySchema.optional(),
      dimension: crmP43HasDimensionSchema.optional(),
      made_of: crmP45ConsistsOfSchema.optional(),
      part_of: crmE22HumanMadeObject1Schema.optional(),
      current_owner: crmP52HasCurrentOwnerSchema.optional(),
      current_custodian: crmP50HasCurrentKeeperSchema.optional(),
      current_permanent_custodian: laCurrentPermanentCustodianSchema.optional(),
      current_location: crmP55HasCurrentLocationSchema.optional(),
      used_for: crmP16IWasUsedFor2Schema.optional(),
      shows: crmP65ShowsVisualItemSchema.optional(),
      carries: crmP128CarriesSchema.optional(),
      produced_by: crmP108IWasProducedBySchema.optional(),
      destroyed_by: crmP13IWasDestroyedBySchema.optional(),
      removed_by: crmP113IWasRemovedBySchema.optional(),
      encountered_by: sciO19IWasObjectEncounteredAtSchema.optional(),
    }).merge(UBBClassExtension).strict(),
  );

export const personSchema: z.ZodSchema<Person> = z.lazy(() =>
  z.object({
    "@context": jSONLDContextSchema,
    id: theSubjectUriSchema,
    type: rdfType26Schema.and(specific38Schema),
    _label: rdfsLabelSchema,
    identified_by: crmP1IsIdentifiedBySchema.optional(),
    classified_as: crmP2HasTypeSchema.optional(),
    referred_to_by: crmP67IIsReferredToBySchema.optional(),
    equivalent: general22Schema.and(specific39Schema).optional(),
    representation: crmP138IHasRepresentationSchema.optional(),
    member_of: crmP107IIsCurrentOrFormerMemberOfSchema.optional(),
    subject_of: crmP129IIsSubjectOfSchema.optional(),
    attributed_by: crmP140IWasAttributedBySchema.optional(),
    carried_out: crmP14IPerformedSchema.optional(),
    contact_point: crmP76HasContactPointSchema.optional(),
    residence: crmP74HasCurrentOrFormerResidenceSchema.optional(),
    born: crmP98IWasBornSchema.optional(),
    died: crmP100IDiedInSchema.optional(),
  }).merge(UBBClassExtension).strict(),
);

export const placeSchemaSchema: z.ZodSchema<PlaceSchema> = z.lazy(() =>
  z.object({
    "@context": jSONLDContextSchema,
    id: theSubjectUriSchema,
    type: rdfType29Schema.and(specific42Schema),
    _label: rdfsLabelSchema,
    classified_as: crmP2HasTypeSchema.optional(),
    identified_by: crmP1IsIdentifiedBySchema.optional(),
    referred_to_by: crmP67IIsReferredToBySchema.optional(),
    equivalent: general23Schema.and(specific43Schema).optional(),
    representation: crmP138IHasRepresentationSchema.optional(),
    member_of: laMemberOfSchema.optional(),
    subject_of: crmP129IIsSubjectOfSchema.optional(),
    attributed_by: crmP140IWasAttributedBySchema.optional(),
    defined_by: crmP168PlaceIsDefinedBySchema.optional(),
    part_of: crmP89FallsWithinSchema.optional(),
  }).merge(UBBClassExtension).strict(),
);

export const provenanceActivitySchemaSchema: z.ZodSchema<ProvenanceActivitySchema> =
  z.lazy(() =>
    z.object({
      "@context": jSONLDContextSchema,
      id: theSubjectUriSchema,
      type: rdfType30Schema.and(specific44Schema),
      _label: rdfsLabelSchema,
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema,
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      equivalent: general24Schema.and(specific45Schema).optional(),
      representation: crmP138IHasRepresentationSchema.optional(),
      member_of: laMemberOfSchema.optional(),
      subject_of: crmP129IIsSubjectOfSchema.optional(),
      attributed_by: crmP140IWasAttributedBySchema.optional(),
      took_place_at: crmP7TookPlaceAtSchema.optional(),
      timespan: crmP4HasTimeSpanSchema.optional(),
      caused_by: sciO13IIsTriggeredBySchema.optional(),
      carried_out_by: crmP14CarriedOutBySchema.optional(),
      used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
      influenced_by: crmP15WasInfluencedBySchema.optional(),
      technique: crmP32UsedGeneralTechniqueSchema.optional(),
      part_of: crmP9IFormsPartOf8Schema.optional(),
      part: crmP9ConsistsOfSchema.optional(),
    }).merge(UBBClassExtension).strict(),
  );

export const collectionSchemaSchema: z.ZodSchema<CollectionSchema> = z.lazy(
  () =>
    z.object({
      "@context": jSONLDContextSchema,
      id: theSubjectUriSchema,
      type: rdfType40Schema.and(specific54Schema),
      _label: rdfsLabelSchema,
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      equivalent: general25Schema.and(specific55Schema).optional(),
      representation: crmP138IHasRepresentationSchema.optional(),
      member_of: laMemberOfSchema.optional(),
      subject_of: crmP129IIsSubjectOfSchema.optional(),
      attributed_by: crmP140IWasAttributedBySchema.optional(),
      dimension: crmP43HasDimensionSchema.optional(),
      about: crmP129IsAboutSchema.optional(),
      members_exemplified_by: z.array(z.unknown()).optional(),
      used_for: crmP16IWasUsedFor3Schema.optional(),
      created_by: crmP94IWasCreatedBy4Schema.optional(),
    }).merge(UBBClassExtension).strict(),
);

export const textSchemaSchema: z.ZodSchema<TextSchema> = z.lazy(() =>
  z.object({
    "@context": jSONLDContextSchema,
    id: theSubjectUriSchema,
    type: rdfType41Schema.and(specific56Schema),
    _label: rdfsLabelSchema,
    identified_by: crmP1IsIdentifiedBySchema.optional(),
    classified_as: crmP2HasTypeSchema.optional(),
    referred_to_by: crmP67IIsReferredToBySchema.optional(),
    equivalent: general26Schema.and(specific57Schema).optional(),
    representation: crmP138IHasRepresentationSchema.optional(),
    member_of: laMemberOfSchema.optional(),
    subject_of: crmP129IIsSubjectOfSchema.optional(),
    attributed_by: crmP140IWasAttributedBySchema.optional(),
    dimension: crmP43HasDimensionSchema.optional(),
    subject_to: crmP104IIsSubjectToSchema.optional(),
    format: dcFormatSchema.optional(),
    language: crmP72HasLanguageSchema.optional(),
    about: crmP129IsAboutSchema.optional(),
    created_by: crmP94IWasCreatedBy5Schema.optional(),
    used_for: crmP16IWasUsedFor4Schema.optional(),
    part_of: crmP106IFormsPartOf1Schema.optional(),
    content: crmP190HasSymbolicContentSchema.optional(),
  }).merge(UBBClassExtension).strict(),
);

export const crmP67IIsReferredToBySchema: z.ZodSchema<CrmP67IIsReferredToBy> =
  z.lazy(() =>
    z.array(
      z.union([
        crmE33LinguisticObjectSchema,
        digD1DigitalObjectSeeSchemaDigitalHtmlSchema,
        crmE33LinguisticObject1Schema,
      ]),
    ),
  );

export const crmE33LinguisticObjectSchema: z.ZodSchema<CrmE33_Linguistic_Object> =
  z.lazy(() =>
    z.object({
      _label: rdfsLabelSchema.optional(),
      type: general4Schema.and(specific3Schema),
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      content: crmP190HasSymbolicContentSchema,
      language: crmP72HasLanguageSchema.optional(),
      format: dcFormatSchema.optional(),
    }).strict(),
  );

export const crmP141IWasAssignedBySchema: z.ZodSchema<CrmP141IWasAssignedBy> =
  z.lazy(() => z.array(crmE13AttributeAssignmentSchema));

export const crmE13AttributeAssignmentSchema: z.ZodSchema<CrmE13_Attribute_Assignment> =
  z.lazy(() =>
    z.object({
      type: general8Schema.and(specific6Schema),
      _label: rdfsLabelSchema.optional(),
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      took_place_at: crmP7TookPlaceAtSchema.optional(),
      timespan: crmP4HasTimeSpanSchema.optional(),
      caused_by: sciO13IIsTriggeredBySchema.optional(),
      carried_out_by: crmP14CarriedOutBySchema.optional(),
      used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
      influenced_by: crmP15WasInfluencedBySchema.optional(),
      technique: crmP32UsedGeneralTechniqueSchema.optional(),
      part_of: z.union([crmE6EventSchema, crmE7ActivitySchema]).optional(),
      assigned: noName1Schema.optional(),
      assigned_property: crmP177AssignedPropertyTypeSchema.optional(),
    }).strict(),
  );

export const crmP32UsedGeneralTechniqueSchema: z.ZodSchema<CrmP32UsedGeneralTechnique> =
  z.lazy(() => z.array(crmE55TypeSchema));

export const crmE55TypeSchema: z.ZodSchema<CrmE55_Type> = z.lazy(() =>
  z.object({
    id: theSubjectUriSchema,
    _label: rdfsLabelSchema.optional(),
    type: general1Schema.and(specific1Schema),
    identified_by: crmP1IsIdentifiedBySchema.optional(),
    classified_as: crmP2HasTypeSchema.optional(),
  }).strict(),
);

export const crmP1IsIdentifiedBySchema: z.ZodSchema<CrmP1IsIdentifiedBy> =
  z.lazy(() =>
    z.array(
      z.union([crmE33E41LinguisticAppellationSchema, crmE42IdentifierSchema]),
    ),
  );

export const crmE33E41LinguisticAppellationSchema: z.ZodSchema<CrmE33_E41_Linguistic_Appellation> =
  z.lazy(() =>
    z.object({
      _label: rdfsLabelSchema.optional(),
      type: general2Schema.and(specific2Schema),
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      content: crmP190HasSymbolicContentSchema,
      language: crmP72HasLanguageSchema.optional(),
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      part: z.array(crmE33E41LinguisticAppellationSchema).optional(),
    }).strict(),
  );

export const crmE42IdentifierSchema: z.ZodSchema<CrmE42_Identifier> = z.lazy(
  () =>
    z.object({
      _label: rdfsLabelSchema.optional(),
      type: general7Schema.and(specific5Schema),
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      content: crmP190HasSymbolicContentSchema,
      part: z.array(crmE42IdentifierSchema).optional(),
      assigned_by: z.array(crmE13AttributeAssignmentSchema).optional(),
    }).strict(),
);

export const crmP2HasTypeSchema: z.ZodSchema<CrmP2HasType> = z.lazy(() =>
  z.array(crmE55TypeSchema),
);

export const laDigitallyShownBySchema: z.ZodSchema<LaDigitallyShownBy> = z.lazy(
  () => z.array(digD1DigitalObjectSchema),
);

export const digD1DigitalObjectSchema: z.ZodSchema<DigD1_Digital_Object> =
  z.lazy(() =>
    z.record(z.unknown()).and(
      z.object({
        type: rdfType6Schema.and(specific16Schema).optional(),
        _label: rdfsLabelSchema.optional(),
        identified_by: crmP1IsIdentifiedBySchema.optional(),
        classified_as: crmP2HasTypeSchema.optional(),
        referred_to_by: crmP67IIsReferredToBySchema.optional(),
        access_point: laAccessPointSchema.optional(),
        format: dcFormatSchema.optional(),
        conforms_to: dctermsConformsToSchema.optional(),
      }).strict(),
    ),
  );

export const crmP138IHasRepresentationSchema: z.ZodSchema<CrmP138IHasRepresentation> =
  z.lazy(() => z.array(crmE36VisualItemSchema));

export const crmE36VisualItemSchema: z.ZodSchema<CrmE36_Visual_Item> = z.lazy(
  () =>
    z.object({
      type: rdfType5Schema.and(specific15Schema),
      _label: rdfsLabelSchema.optional(),
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      digitally_shown_by: laDigitallyShownBySchema.optional(),
    }).strict(),
);

export const laDigitallyCarriedBySchema: z.ZodSchema<LaDigitallyCarriedBy> =
  z.lazy(() => z.array(digD1DigitalObjectSchema));

export const crmP129IIsSubjectOfSchema: z.ZodSchema<CrmP129IIsSubjectOf> =
  z.lazy(() => z.array(crmE33LinguisticObject2Schema));

export const crmE33LinguisticObject2Schema: z.ZodSchema<CrmE33_Linguistic_Object2> =
  z.lazy(() =>
    z.object({
      id: theSubjectUriSchema.optional(),
      type: rdfType8Schema.and(specific17Schema),
      _label: rdfsLabelSchema.optional(),
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      language: crmP72HasLanguageSchema.optional(),
      digitally_carried_by: laDigitallyCarriedBySchema.optional(),
      content: crmP190HasSymbolicContentSchema.optional(),
    }).strict(),
  );

export const crmP140IWasAttributedBySchema: z.ZodSchema<CrmP140IWasAttributedBy> =
  z.lazy(() => z.array(crmE13AttributeAssignmentSchema));

export const crmP43HasDimensionSchema: z.ZodSchema<CrmP43HasDimension> = z.lazy(
  () => z.array(crmE54DimensionSchema),
);

export const crmE54DimensionSchema: z.ZodSchema<CrmE54_Dimension> = z.lazy(() =>
  z.object({
    _label: rdfsLabelSchema.optional(),
    type: general11Schema.and(specific9Schema),
    identified_by: crmP1IsIdentifiedBySchema.optional(),
    classified_as: crmP2HasTypeSchema.optional(),
    value: crmP90HasValueSchema,
    lower_value_limit: crmP90AHasLowerValueLimitSchema.optional(),
    upper_value_limit: crmP90AHasUpperValueLimitSchema.optional(),
    unit: crmP91HasUnitSchema,
    assigned_by: crmP141IWasAssignedBySchema.optional(),
  }).strict(),
);

export const laDigitallyAvailableViaSchema: z.ZodSchema<LaDigitallyAvailableVia> =
  z.lazy(() => z.array(laDigitalServiceSchema));

export const laDigitalServiceSchema: z.ZodSchema<LaDigitalService> = z.lazy(
  () =>
    z.record(z.unknown()).and(
      z.object({
        type: rdfType11Schema.and(specific21Schema).optional(),
        _label: rdfsLabelSchema.optional(),
        identified_by: crmP1IsIdentifiedBySchema.optional(),
        classified_as: crmP2HasTypeSchema.optional(),
        referred_to_by: crmP67IIsReferredToBySchema.optional(),
        access_point: laAccessPointSchema.optional(),
        conforms_to: dctermsConformsToSchema.optional(),
      }).strict(),
    ),
);

export const crmP16IWasUsedForSchema: z.ZodSchema<CrmP16IWasUsedFor> = z.lazy(
  () => z.array(crmE7Activity1Schema),
);

export const crmE7Activity1Schema: z.ZodSchema<CrmE7_Activity1> = z.lazy(() =>
  z.object({
    type: rdfType13Schema.and(specific22Schema),
    _label: rdfsLabelSchema.optional(),
    identified_by: crmP1IsIdentifiedBySchema.optional(),
    classified_as: crmP2HasTypeSchema.optional(),
    referred_to_by: crmP67IIsReferredToBySchema.optional(),
    took_place_at: crmP7TookPlaceAtSchema.optional(),
    timespan: crmP4HasTimeSpanSchema.optional(),
    caused_by: sciO13IIsTriggeredBySchema.optional(),
    carried_out_by: crmP14CarriedOutBySchema.optional(),
    used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
    influenced_by: crmP15WasInfluencedBySchema.optional(),
    technique: crmP32UsedGeneralTechniqueSchema.optional(),
    part_of: z.union([crmE6EventSchema, crmE7ActivitySchema]).optional(),
  }).strict(),
);

export const crmP14IPerformedSchema: z.ZodSchema<CrmP14IPerformed> = z.lazy(
  () => z.array(crmE7Activity1Schema),
);

export const crmP76HasContactPointSchema: z.ZodSchema<CrmP76HasContactPoint> =
  z.lazy(() => z.array(crmE42IdentifierSchema));

export const crmP104IIsSubjectToSchema: z.ZodSchema<CrmP104IIsSubjectTo> =
  z.lazy(() => z.array(crmE30RightSchema));

export const crmE30RightSchema: z.ZodSchema<CrmE30_Right> = z.lazy(() =>
  z.object({
    id: theSubjectUriSchema,
    _label: rdfsLabelSchema.optional(),
    type: rdfType19Schema.and(specific31Schema),
    identified_by: crmP1IsIdentifiedBySchema.optional(),
    classified_as: crmP2HasTypeSchema.optional(),
    referred_to_by: crmP67IIsReferredToBySchema.optional(),
    created_by: crmP94IWasCreatedBy2Schema.optional(),
    possessed_by: z
      .array(z.union([e21PersonSchema, crmE74GroupSchema]))
      .optional(),
    subject_of: crmP129IIsSubjectOfSchema.optional(),
  }).merge(UBBRightExtension).strict(),
);

export const laRepresentsInstanceOfTypeSchema: z.ZodSchema<LaRepresentsInstanceOfType> =
  z.lazy(() => z.array(crmE55TypeSchema));

export const crmP16IWasUsedFor1Schema: z.ZodSchema<CrmP16IWasUsedFor1> = z.lazy(
  () => z.array(crmE7Activity1Schema),
);

export const crmP16IWasUsedFor2Schema: z.ZodSchema<CrmP16IWasUsedFor2> = z.lazy(
  () => z.array(crmE7Activity1Schema),
);

export const crmP46IsComposedOfSchema: z.ZodSchema<CrmP46IsComposedOf> = z.lazy(
  () => z.array(crmE12ProductionSchema),
);

export const crmE12ProductionSchema: z.ZodSchema<CrmE12_Production> = z.lazy(
  () =>
    z.record(z.unknown()).and(
      z.object({
        type: rdfType22Schema.and(specific34Schema).optional(),
        _label: rdfsLabelSchema.optional(),
        identified_by: crmP1IsIdentifiedBySchema.optional(),
        classified_as: crmP2HasTypeSchema.optional(),
        referred_to_by: crmP67IIsReferredToBySchema.optional(),
        took_place_at: crmP7TookPlaceAtSchema.optional(),
        timespan: crmP4HasTimeSpanSchema.optional(),
        caused_by: sciO13IIsTriggeredBySchema.optional(),
        carried_out_by: crmP14CarriedOutBySchema.optional(),
        used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
        influenced_by: crmP15WasInfluencedBySchema.optional(),
        technique: crmP32UsedGeneralTechniqueSchema.optional(),
        part_of: crmP9IFormsPartOf4Schema.optional(),
        part: crmP46IsComposedOfSchema.optional(),
      }).strict(),
    ),
);

export const crmP113IWasRemovedBySchema: z.ZodSchema<CrmP113IWasRemovedBy> =
  z.lazy(() => z.array(crmE80PartRemovalSchema));

export const crmE80PartRemovalSchema: z.ZodSchema<CrmE80_Part_Removal> = z.lazy(
  () =>
    z.record(z.unknown()).and(
      z.object({
        type: rdfType24Schema.and(specific36Schema).optional(),
        _label: rdfsLabelSchema.optional(),
        identified_by: crmP1IsIdentifiedBySchema.optional(),
        classified_as: crmP2HasTypeSchema.optional(),
        referred_to_by: crmP67IIsReferredToBySchema.optional(),
        took_place_at: crmP7TookPlaceAtSchema.optional(),
        timespan: crmP4HasTimeSpanSchema.optional(),
        caused_by: sciO13IIsTriggeredBySchema.optional(),
        carried_out_by: crmP14CarriedOutBySchema.optional(),
        used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
        influenced_by: crmP15WasInfluencedBySchema.optional(),
        technique: crmP32UsedGeneralTechniqueSchema.optional(),
        part_of: crmP9IFormsPartOf6Schema.optional(),
        diminished: crmE22HumanMadeObject2Schema.optional(),
      }).strict(),
    ),
);

export const sciO19IWasObjectEncounteredAtSchema: z.ZodSchema<SciO19IWasObjectEncounteredAt> =
  z.lazy(() => z.array(sciS19EncounterEventSchema));

export const sciS19EncounterEventSchema: z.ZodSchema<SciS19_Encounter_Event> =
  z.lazy(() =>
    z.record(z.unknown()).and(
      z.object({
        type: rdfType25Schema.and(specific37Schema).optional(),
        _label: rdfsLabelSchema.optional(),
        identified_by: crmP1IsIdentifiedBySchema.optional(),
        classified_as: crmP2HasTypeSchema.optional(),
        referred_to_by: crmP67IIsReferredToBySchema.optional(),
        took_place_at: crmP7TookPlaceAtSchema.optional(),
        timespan: crmP4HasTimeSpanSchema.optional(),
        caused_by: sciO13IIsTriggeredBySchema.optional(),
        carried_out_by: crmP14CarriedOutBySchema.optional(),
        used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
        influenced_by: crmP15WasInfluencedBySchema.optional(),
        technique: crmP32UsedGeneralTechniqueSchema.optional(),
        part_of: crmP9IFormsPartOf7Schema.optional(),
      }).strict(),
    ),
  );

export const laEstablishesSchema: z.ZodSchema<LaEstablishes> = z.lazy(() =>
  z.array(crmE30RightSchema),
);

export const laInvalidatesSchema: z.ZodSchema<LaInvalidates> = z.lazy(() =>
  z.array(crmE30RightSchema),
);

export const crmP9ConsistsOfSchema: z.ZodSchema<CrmP9ConsistsOf> = z.lazy(() =>
  z.array(
    z.union([
      crmE8AcquisitionSchema,
      laRightAcquisitionSchema,
      crmE10TransferOfCustodySchema,
      laPaymentSchema,
      sciS19EncounterEvent1Schema,
      crmE9MoveSchema,
      crmE7Activity2Schema,
    ]),
  ),
);

export const crmE8AcquisitionSchema: z.ZodSchema<CrmE8_Acquisition> = z.lazy(
  () =>
    z.object({
      type: rdfType31Schema.and(specific46Schema),
      _label: rdfsLabelSchema.optional(),
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      took_place_at: crmP7TookPlaceAtSchema.optional(),
      timespan: crmP4HasTimeSpanSchema.optional(),
      caused_by: sciO13IIsTriggeredBySchema.optional(),
      carried_out_by: crmP14CarriedOutBySchema.optional(),
      used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
      influenced_by: crmP15WasInfluencedBySchema.optional(),
      technique: crmP32UsedGeneralTechniqueSchema.optional(),
      transferred_title_from: crmP23TransferredTitleFromSchema.optional(),
      transferred_title_to: crmP22TransferredTitleToSchema.optional(),
      transferred_title_of: crmP24TransferredTitleOfSchema,
    }).strict(),
);

export const laRightAcquisitionSchema: z.ZodSchema<LaRightAcquisition> = z.lazy(
  () =>
    z.object({
      type: rdfType32Schema.and(specific47Schema),
      _label: rdfsLabelSchema.optional(),
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      took_place_at: crmP7TookPlaceAtSchema.optional(),
      timespan: crmP4HasTimeSpanSchema.optional(),
      caused_by: sciO13IIsTriggeredBySchema.optional(),
      carried_out_by: crmP14CarriedOutBySchema.optional(),
      used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
      influenced_by: crmP15WasInfluencedBySchema.optional(),
      technique: crmP32UsedGeneralTechniqueSchema.optional(),
      establishes: laEstablishesSchema,
      invalidates: laInvalidatesSchema.optional(),
    }).strict(),
);

export const crmE10TransferOfCustodySchema: z.ZodSchema<CrmE10_TransferOf_Custody> =
  z.lazy(() =>
    z.object({
      type: rdfType33Schema.and(specific48Schema),
      _label: rdfsLabelSchema.optional(),
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      took_place_at: crmP7TookPlaceAtSchema.optional(),
      timespan: crmP4HasTimeSpanSchema.optional(),
      caused_by: sciO13IIsTriggeredBySchema.optional(),
      carried_out_by: crmP14CarriedOutBySchema.optional(),
      used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
      influenced_by: crmP15WasInfluencedBySchema.optional(),
      technique: crmP32UsedGeneralTechniqueSchema.optional(),
      transferred_custody_from: crmP28CustodySurrenderedBySchema.optional(),
      transferred_custody_to: crmP29CustodyReceivedBySchema.optional(),
      transferred_custody_of: crmP30TransferredCustodyOfSchema,
    }).strict(),
  );

export const laPaymentSchema: z.ZodSchema<LaPayment> = z.lazy(() =>
  z.object({
    type: rdfType34Schema.and(specific49Schema),
    _label: rdfsLabelSchema.optional(),
    identified_by: crmP1IsIdentifiedBySchema.optional(),
    classified_as: crmP2HasTypeSchema.optional(),
    referred_to_by: crmP67IIsReferredToBySchema.optional(),
    took_place_at: crmP7TookPlaceAtSchema.optional(),
    timespan: crmP4HasTimeSpanSchema.optional(),
    caused_by: sciO13IIsTriggeredBySchema.optional(),
    carried_out_by: crmP14CarriedOutBySchema.optional(),
    used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
    influenced_by: crmP15WasInfluencedBySchema.optional(),
    technique: crmP32UsedGeneralTechniqueSchema.optional(),
    paid_from: laPaidFromSchema.optional(),
    paid_to: laPaidToSchema.optional(),
    paid_amount: laPaidAmountSchema.optional(),
  }).strict(),
);

export const sciS19EncounterEvent1Schema: z.ZodSchema<SciS19_Encounter_Event1> =
  z.lazy(() =>
    z.object({
      type: rdfType37Schema.and(specific51Schema),
      _label: rdfsLabelSchema.optional(),
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      took_place_at: crmP7TookPlaceAtSchema.optional(),
      timespan: crmP4HasTimeSpanSchema.optional(),
      caused_by: sciO13IIsTriggeredBySchema.optional(),
      carried_out_by: crmP14CarriedOutBySchema.optional(),
      used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
      influenced_by: crmP15WasInfluencedBySchema.optional(),
      technique: crmP32UsedGeneralTechniqueSchema.optional(),
      encountered: sciO19HasFoundObjectSchema,
    }).strict(),
  );

export const crmE9MoveSchema: z.ZodSchema<CrmE9_Move> = z.lazy(() =>
  z.object({
    type: rdfType38Schema.and(specific52Schema),
    _label: rdfsLabelSchema.optional(),
    identified_by: crmP1IsIdentifiedBySchema.optional(),
    classified_as: crmP2HasTypeSchema.optional(),
    referred_to_by: crmP67IIsReferredToBySchema.optional(),
    took_place_at: crmP7TookPlaceAtSchema.optional(),
    timespan: crmP4HasTimeSpanSchema.optional(),
    caused_by: sciO13IIsTriggeredBySchema.optional(),
    carried_out_by: crmP14CarriedOutBySchema.optional(),
    used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
    influenced_by: crmP15WasInfluencedBySchema.optional(),
    technique: crmP32UsedGeneralTechniqueSchema.optional(),
    moved_from: crmE53Place1Schema.optional(),
    moved_to: crmE53Place2Schema.optional(),
    moved: crmP25MovedSchema,
  }).strict(),
);

export const crmE7Activity2Schema: z.ZodSchema<CrmE7_Activity2> = z.lazy(() =>
  z.object({
    type: rdfType39Schema.and(specific53Schema),
    _label: rdfsLabelSchema.optional(),
    identified_by: crmP1IsIdentifiedBySchema.optional(),
    classified_as: crmP2HasTypeSchema,
    referred_to_by: crmP67IIsReferredToBySchema.optional(),
    took_place_at: crmP7TookPlaceAtSchema.optional(),
    timespan: crmP4HasTimeSpanSchema.optional(),
    caused_by: sciO13IIsTriggeredBySchema.optional(),
    carried_out_by: crmP14CarriedOutBySchema.optional(),
    used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
    influenced_by: crmP15WasInfluencedBySchema.optional(),
    technique: crmP32UsedGeneralTechniqueSchema.optional(),
  }).strict(),
);

export const crmP16IWasUsedFor3Schema: z.ZodSchema<CrmP16IWasUsedFor3> = z.lazy(
  () => z.array(crmE7Activity1Schema),
);

export const crmP16IWasUsedFor4Schema: z.ZodSchema<CrmP16IWasUsedFor4> = z.lazy(
  () => z.array(crmE7Activity1Schema),
);

export const crmP94IWasCreatedBySchema: z.ZodSchema<CrmP94IWasCreatedBy> =
  z.lazy(() =>
    z.record(z.unknown()).and(
      z.object({
        type: rdfType9Schema.and(specific18Schema).optional(),
        _label: rdfsLabelSchema.optional(),
        identified_by: crmP1IsIdentifiedBySchema.optional(),
        classified_as: crmP2HasTypeSchema.optional(),
        referred_to_by: crmP67IIsReferredToBySchema.optional(),
        took_place_at: crmP7TookPlaceAtSchema.optional(),
        timespan: crmP4HasTimeSpanSchema.optional(),
        caused_by: sciO13IIsTriggeredBySchema.optional(),
        carried_out_by: crmP14CarriedOutBySchema.optional(),
        used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
        influenced_by: crmP15WasInfluencedBySchema.optional(),
        technique: crmP32UsedGeneralTechniqueSchema.optional(),
        part_of: crmP9IFormsPartOfSchema.optional(),
      }).strict(),
    ),
  );

export const crmP4HasTimeSpanSchema: z.ZodSchema<CrmP4HasTimeSpan> = z.lazy(
  () =>
    z.object({
      _label: rdfsLabelSchema.optional(),
      type: general10Schema.and(specific8Schema),
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      begin_of_the_begin: crmP82ABeginOfTheBeginSchema.optional(),
      end_of_the_begin: crmP81AEndOfTheBeginSchema.optional(),
      begin_of_the_end: crmP81BBeginOfTheEndSchema.optional(),
      end_of_the_end: crmP82BEndOfTheEndSchema.optional(),
      duration: crmP191HadDurationSchema.optional(),
    }).merge(UBBTimeSpanExtension).strict(),
);

export const crmP191HadDurationSchema: z.ZodSchema<CrmP191HadDuration> = z.lazy(
  () =>
    z.object({
      _label: rdfsLabelSchema.optional(),
      type: general11Schema.and(specific9Schema),
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      value: crmP90HasValueSchema,
      lower_value_limit: crmP90AHasLowerValueLimitSchema.optional(),
      upper_value_limit: crmP90AHasUpperValueLimitSchema.optional(),
      unit: crmP91HasUnitSchema,
      assigned_by: crmP141IWasAssignedBySchema.optional(),
    }),
);

export const crmP94IWasCreatedBy1Schema: z.ZodSchema<CrmP94IWasCreatedBy1> =
  z.lazy(() =>
    z.record(z.unknown()).and(
      z.object({
        type: rdfType9Schema.and(specific18Schema).optional(),
        _label: rdfsLabelSchema.optional(),
        identified_by: crmP1IsIdentifiedBySchema.optional(),
        classified_as: crmP2HasTypeSchema.optional(),
        referred_to_by: crmP67IIsReferredToBySchema.optional(),
        took_place_at: crmP7TookPlaceAtSchema.optional(),
        timespan: crmP4HasTimeSpanSchema.optional(),
        caused_by: sciO13IIsTriggeredBySchema.optional(),
        carried_out_by: crmP14CarriedOutBySchema.optional(),
        used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
        influenced_by: crmP15WasInfluencedBySchema.optional(),
        technique: crmP32UsedGeneralTechniqueSchema.optional(),
        part_of: crmP9IFormsPartOfSchema.optional(),
      }),
    ),
  );

export const crmP95IWasFormedBySchema: z.ZodSchema<CrmP95IWasFormedBy> = z.lazy(
  () =>
    z.record(z.unknown()).and(
      z.object({
        type: rdfType16Schema.and(specific27Schema).optional(),
        _label: rdfsLabelSchema.optional(),
        identified_by: crmP1IsIdentifiedBySchema.optional(),
        classified_as: crmP2HasTypeSchema.optional(),
        referred_to_by: crmP67IIsReferredToBySchema.optional(),
        took_place_at: crmP7TookPlaceAtSchema.optional(),
        timespan: crmP4HasTimeSpanSchema.optional(),
        caused_by: sciO13IIsTriggeredBySchema.optional(),
        carried_out_by: crmP14CarriedOutBySchema.optional(),
        used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
        influenced_by: crmP15WasInfluencedBySchema.optional(),
        technique: crmP32UsedGeneralTechniqueSchema.optional(),
        part_of: crmP9IFormsPartOf2Schema.optional(),
      }),
    ),
);

export const crmP99IWasDissolvedBySchema: z.ZodSchema<CrmP99IWasDissolvedBy> =
  z.lazy(() =>
    z.record(z.unknown()).and(
      z.object({
        type: rdfType17Schema.and(specific28Schema).optional(),
        _label: rdfsLabelSchema.optional(),
        identified_by: crmP1IsIdentifiedBySchema.optional(),
        classified_as: crmP2HasTypeSchema.optional(),
        referred_to_by: crmP67IIsReferredToBySchema.optional(),
        took_place_at: crmP7TookPlaceAtSchema.optional(),
        timespan: crmP4HasTimeSpanSchema.optional(),
        caused_by: sciO13IIsTriggeredBySchema.optional(),
        influenced_by: crmP15WasInfluencedBySchema.optional(),
        part_of: crmP9IFormsPartOf3Schema.optional(),
      }),
    ),
  );

export const crmP94IWasCreatedBy3Schema: z.ZodSchema<CrmP94IWasCreatedBy3> =
  z.lazy(() =>
    z.record(z.unknown()).and(
      z.object({
        type: rdfType9Schema.and(specific18Schema).optional(),
        _label: rdfsLabelSchema.optional(),
        identified_by: crmP1IsIdentifiedBySchema.optional(),
        classified_as: crmP2HasTypeSchema.optional(),
        referred_to_by: crmP67IIsReferredToBySchema.optional(),
        took_place_at: crmP7TookPlaceAtSchema.optional(),
        timespan: crmP4HasTimeSpanSchema.optional(),
        caused_by: sciO13IIsTriggeredBySchema.optional(),
        carried_out_by: crmP14CarriedOutBySchema.optional(),
        used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
        influenced_by: crmP15WasInfluencedBySchema.optional(),
        technique: crmP32UsedGeneralTechniqueSchema.optional(),
        part_of: crmP9IFormsPartOfSchema.optional(),
      }),
    ),
  );

export const crmP94IWasCreatedBy2Schema: z.ZodSchema<CrmP94IWasCreatedBy2> =
  z.lazy(() =>
    z.record(z.unknown()).and(
      z.object({
        type: rdfType9Schema.and(specific18Schema).optional(),
        _label: rdfsLabelSchema.optional(),
        identified_by: crmP1IsIdentifiedBySchema.optional(),
        classified_as: crmP2HasTypeSchema.optional(),
        referred_to_by: crmP67IIsReferredToBySchema.optional(),
        took_place_at: crmP7TookPlaceAtSchema.optional(),
        timespan: crmP4HasTimeSpanSchema.optional(),
        caused_by: sciO13IIsTriggeredBySchema.optional(),
        carried_out_by: crmP14CarriedOutBySchema.optional(),
        used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
        influenced_by: crmP15WasInfluencedBySchema.optional(),
        technique: crmP32UsedGeneralTechniqueSchema.optional(),
        part_of: crmP9IFormsPartOfSchema.optional(),
      }),
    ),
  );

export const crmP108IWasProducedBySchema: z.ZodSchema<CrmP108IWasProducedBy> =
  z.lazy(() =>
    z.record(z.unknown()).and(
      z.object({
        type: rdfType22Schema.and(specific34Schema).optional(),
        _label: rdfsLabelSchema.optional(),
        identified_by: crmP1IsIdentifiedBySchema.optional(),
        classified_as: crmP2HasTypeSchema.optional(),
        referred_to_by: crmP67IIsReferredToBySchema.optional(),
        took_place_at: crmP7TookPlaceAtSchema.optional(),
        timespan: crmP4HasTimeSpanSchema.optional(),
        caused_by: sciO13IIsTriggeredBySchema.optional(),
        carried_out_by: crmP14CarriedOutBySchema.optional(),
        used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
        influenced_by: crmP15WasInfluencedBySchema.optional(),
        technique: crmP32UsedGeneralTechniqueSchema.optional(),
        part_of: crmP9IFormsPartOf4Schema.optional(),
        part: crmP46IsComposedOfSchema.optional(),
      }),
    ),
  );

export const crmP13IWasDestroyedBySchema: z.ZodSchema<CrmP13IWasDestroyedBy> =
  z.lazy(() =>
    z.record(z.unknown()).and(
      z.object({
        type: rdfType23Schema.and(specific35Schema).optional(),
        _label: rdfsLabelSchema.optional(),
        identified_by: crmP1IsIdentifiedBySchema.optional(),
        classified_as: crmP2HasTypeSchema.optional(),
        referred_to_by: crmP67IIsReferredToBySchema.optional(),
        took_place_at: crmP7TookPlaceAtSchema.optional(),
        timespan: crmP4HasTimeSpanSchema.optional(),
        caused_by: sciO13IIsTriggeredBySchema.optional(),
        part_of: crmP9IFormsPartOf5Schema.optional(),
      }),
    ),
  );

export const crmP98IWasBornSchema: z.ZodSchema<CrmP98IWasBorn> = z.lazy(() =>
  z.record(z.unknown()).and(
    z.object({
      type: rdfType27Schema.and(specific40Schema).optional(),
      _label: rdfsLabelSchema.optional(),
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      took_place_at: crmP7TookPlaceAtSchema.optional(),
      timespan: crmP4HasTimeSpanSchema.optional(),
      caused_by: sciO13IIsTriggeredBySchema.optional(),
    }),
  ),
);

export const crmP100IDiedInSchema: z.ZodSchema<CrmP100IDiedIn> = z.lazy(() =>
  z.record(z.unknown()).and(
    z.object({
      type: rdfType28Schema.and(specific41Schema).optional(),
      _label: rdfsLabelSchema.optional(),
      identified_by: crmP1IsIdentifiedBySchema.optional(),
      classified_as: crmP2HasTypeSchema.optional(),
      referred_to_by: crmP67IIsReferredToBySchema.optional(),
      took_place_at: crmP7TookPlaceAtSchema.optional(),
      timespan: crmP4HasTimeSpanSchema.optional(),
      caused_by: sciO13IIsTriggeredBySchema.optional(),
    }),
  ),
);

export const laPaidAmountSchema: z.ZodSchema<LaPaidAmount> = z.lazy(() =>
  z.object({
    _label: rdfsLabelSchema.optional(),
    type: rdfType35Schema.and(specific50Schema),
    identified_by: crmP1IsIdentifiedBySchema.optional(),
    classified_as: crmP2HasTypeSchema.optional(),
    value: crmP90HasValueSchema,
    lower_value_limit: crmP90AHasLowerValueLimitSchema.optional(),
    upper_value_limit: crmP90AHasUpperValueLimitSchema.optional(),
    currency: crmE98CurrencySchema,
  }),
);

export const crmP94IWasCreatedBy4Schema: z.ZodSchema<CrmP94IWasCreatedBy4> =
  z.lazy(() =>
    z.record(z.unknown()).and(
      z.object({
        type: rdfType9Schema.and(specific18Schema).optional(),
        _label: rdfsLabelSchema.optional(),
        identified_by: crmP1IsIdentifiedBySchema.optional(),
        classified_as: crmP2HasTypeSchema.optional(),
        referred_to_by: crmP67IIsReferredToBySchema.optional(),
        took_place_at: crmP7TookPlaceAtSchema.optional(),
        timespan: crmP4HasTimeSpanSchema.optional(),
        caused_by: sciO13IIsTriggeredBySchema.optional(),
        carried_out_by: crmP14CarriedOutBySchema.optional(),
        used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
        influenced_by: crmP15WasInfluencedBySchema.optional(),
        technique: crmP32UsedGeneralTechniqueSchema.optional(),
        part_of: crmP9IFormsPartOfSchema.optional(),
      }),
    ),
  );

export const crmP94IWasCreatedBy5Schema: z.ZodSchema<CrmP94IWasCreatedBy5> =
  z.lazy(() =>
    z.record(z.unknown()).and(
      z.object({
        type: rdfType9Schema.and(specific18Schema).optional(),
        _label: rdfsLabelSchema.optional(),
        identified_by: crmP1IsIdentifiedBySchema.optional(),
        classified_as: crmP2HasTypeSchema.optional(),
        referred_to_by: crmP67IIsReferredToBySchema.optional(),
        took_place_at: crmP7TookPlaceAtSchema.optional(),
        timespan: crmP4HasTimeSpanSchema.optional(),
        caused_by: sciO13IIsTriggeredBySchema.optional(),
        carried_out_by: crmP14CarriedOutBySchema.optional(),
        used_specific_object: crmP16UsedSpecificObjectSchema.optional(),
        influenced_by: crmP15WasInfluencedBySchema.optional(),
        technique: crmP32UsedGeneralTechniqueSchema.optional(),
        part_of: crmP9IFormsPartOfSchema.optional(),
      }),
    ),
  );
