import type { NextRequest } from 'next/server'
import { datasetPresentation } from '@/config/metadata-config'
import {
  fetchGitAppRawFile,
  getBaseUrlFromRequestHeaders,
  rewriteSitemapLocOrigins,
} from '@/app/(sitemap)/git-app'

function escapeXml(s: string): string {
  return s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;')
}

function urlsetXml(urls: string[]): string {
  const entries = urls.map((u) => `  <url><loc>${escapeXml(u)}</loc></url>`).join('\n')
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    entries,
    '</urlset>',
    '',
  ].join('\n')
}

export async function GET(request: NextRequest, ctx: { params: Promise<{ name: string }> }) {
  const { name } = await ctx.params

  // Only allow flat filenames, e.g. `sitemap-foo.xml`
  if (typeof name !== 'string' || name.includes('/') || !name.endsWith('.xml')) {
    return new Response('Not found', { status: 404 })
  }

  const baseUrl = getBaseUrlFromRequestHeaders(request.headers)

  // `sitemap-base.xml` is intentionally generated by the frontend, not stored in git.
  if (name === 'sitemap-base.xml') {
    const metaPages = [
      `${baseUrl}/`,
      `${baseUrl}/info`,
      `${baseUrl}/iiif`,
      `${baseUrl}/help`,
      `${baseUrl}/datasets`,
    ]

    const datasetPages = Object.keys(datasetPresentation)
      .filter((dataset) => dataset !== 'all')
      .map((dataset) => `${baseUrl}/info/datasets/${dataset.split('_')[0]}`)

    return new Response(urlsetXml([...metaPages, ...datasetPages]), {
      status: 200,
      headers: {
        'content-type': 'application/xml; charset=utf-8',
        'cache-control': 'public, max-age=0, s-maxage=3600',
      },
    })
  }

  const raw = await fetchGitAppRawFile({
    path: `lfs-data/sitemap/sitemaps/${name}`,
  })

  if (!raw.ok) {
    return new Response(raw.error, {
      status: raw.status,
      headers: { 'content-type': 'text/plain; charset=utf-8' },
    })
  }

  const xml = rewriteSitemapLocOrigins(raw.content, baseUrl)
  return new Response(xml, {
    status: 200,
    headers: {
      'content-type': 'application/xml; charset=utf-8',
      'cache-control': 'public, max-age=0, s-maxage=3600',
    },
  })
}


