import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import NavBar from "./NavBar";
import { PT_Sans, EB_Garamond } from 'next/font/google'
import SearchBar from "./SearchBar"
 
const garamond = EB_Garamond({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-garamond',
})
 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="no" className={`${garamond.variable} h-full`}>
      <body className="flex flex-col h-full">
        <header className="flex flex-col md:flex-row gap-3 p-3 px-3 text-slate-900">
          <div className="flex justify-between">
          <Link href="/" className="sm:text-xl md:text-2xl font-garamond small-caps">Norske stadnamn</Link>
          <NavBar/>
          </div>
          <SearchBar/> 
                  
          


        </header>
        {children}
      </body>
    </html>
  );
}
