/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * All Linked Art Records
 */
export type LinkedArtSchema =
  | ConceptSchema
  | DigitalObjectSchema
  | EventSchema
  | GroupSchema
  | VisualContentSchema
  | HumanMadeObjectSchema
  | Person
  | PlaceSchema
  | ProvenanceActivitySchema
  | CollectionSchema
  | TextSchema;
/**
 * Either an array of contexts, or a string containing the Linked Art context URI
 */
export type JSONLDContext = LinkedArt | LinkedArtWithExtensions;
export type LinkedArt = "https://linked.art/ns/v1/linked-art.json";
export type LinkedArtWithExtensions = string[];
/**
 * The URI of the entity
 */
export type TheSubjectUri = string;
/**
 * The class of the entity
 */
export type General = string;
export type Specific = "Type" | "Currency" | "Material" | "Language" | "MeasurementUnit";
/**
 * A human readable name or label for the entity, intended for developers
 */
export type RdfsLabel = Partial<string | Record<string, string[]> | undefined>;
/**
 * The class of the entity
 */
export type General1 = string;
export type Specific1 = "Type";
/**
 * The class of the entity
 */
export type General2 = string;
export type Specific2 = "Name";
/**
 * The string representation of a `Name`, `Identifier`, `Statement` or other text
 */
export type CrmP190HasSymbolicContent = string;
/**
 * The class of the entity
 */
export type General3 = string;
/**
 * A reference to one or more `Language` entities in which the `content` of this text is written
 */
export type CrmP72HasLanguage = CrmE56_Language[];
/**
 * The class of the entity
 */
export type General4 = string;
export type Specific3 = "LinguisticObject";
/**
 * The media type of the content of the embedded text, e.g. text/plain
 */
export type DcFormat = string;
/**
 * The class of the entity
 */
export type General5 = string;
export type Specific4 = "DigitalObject";
/**
 * The class of the entity
 */
export type General6 = string;
/**
 * An embedded statement about this entity, or a reference to a text that refers to the entity
 */
export type CrmP67IIsReferredToBy = (
  | CrmE33_Linguistic_Object
  | DigD1_Digital_ObjectSeeSchemaDigitalHtml
  | CrmE33_Linguistic_Object1
)[];
/**
 * The class of the entity
 */
export type General7 = string;
export type Specific5 = "Identifier";
/**
 * The class of the entity
 */
export type General8 = string;
export type Specific6 = "AttributeAssignment";
/**
 * The class of the entity
 */
export type General9 = string;
export type Specific7 = "Place";
/**
 * A `Place` at which this event occured
 */
export type CrmP7TookPlaceAt = CrmE53_Place[];
/**
 * The class of the entity
 */
export type General10 = string;
export type Specific8 = "TimeSpan";
/**
 * The earliest possible date-time at which the timespan could have started
 */
export type CrmP82ABeginOfTheBegin = string;
/**
 * The latest possible date-time at which the timespan could have started
 */
export type CrmP81AEndOfTheBegin = string;
/**
 * The earliest possible date-time at which the timespan could have ended
 */
export type CrmP81BBeginOfTheEnd = string;
/**
 * The latest possible date-time at which the timespan could have ended
 */
export type CrmP82BEndOfTheEnd = string;
/**
 * The class of the entity
 */
export type General11 = string;
export type Specific9 = "Dimension";
/**
 * The numeric value of a `Dimension` or `MonetaryAmount`
 */
export type CrmP90HasValue = number;
/**
 * The lowest possible value for the `Dimension` or `MonetaryAmount`
 */
export type CrmP90AHasLowerValueLimit = number;
/**
 * The highest possible value for the `Dimension` or `MonetaryAmount`
 */
export type CrmP90AHasUpperValueLimit = number;
/**
 * The class of the entity
 */
export type General12 = string;
/**
 * The Measurement(s) that led to the assigning of this dimension
 */
export type CrmP141IWasAssignedBy = CrmE13_Attribute_Assignment[];
/**
 * The class of the entity
 */
export type General13 = string;
/**
 * The class of the entity
 */
export type General14 = string;
/**
 * Another event which caused this event to occur
 */
export type SciO13IIsTriggeredBy = (CrmE6_Event | CrmE7_Activity)[];
/**
 * The class of the entity
 */
export type General15 = string;
export type Specific10 = "Person";
/**
 * The class of the entity
 */
export type RdfType = string;
export type Specific11 = "Group";
/**
 * A reference to a Person or Group which carried out this activity
 */
export type CrmP14CarriedOutBy = (E21_Person | CrmE74_Group)[];
/**
 * The class of the entity
 */
export type RdfType1 = string;
export type Specific12 = "HumanMadeObject";
/**
 * The class of the entity
 */
export type RdfType2 = string;
/**
 * An object or set of things which was used to carry out this activity
 */
export type CrmP16UsedSpecificObject = (CrmE22_HumanMade_Object | LaSet)[];
/**
 * The class of the entity
 */
export type RdfType3 = string;
export type Specific13 =
  | "HumanMadeObject"
  | "Person"
  | "Group"
  | "VisualItem"
  | "LinguisticObject"
  | "Set"
  | "Place"
  | "DigitalObject"
  | "Type"
  | "Event"
  | "Activity"
  | "Period";
/**
 * An entity that influenced the activity in some way
 */
export type CrmP15WasInfluencedBy = NoName[];
/**
 * A general technique that was employed to carry out this activity
 */
export type CrmP32UsedGeneralTechnique = CrmE55_Type[];
/**
 * The relationship from the attributed entity to the assigned entity, given as a string which resolves to a relationship in the context definition
 */
export type CrmP177AssignedPropertyType = string;
/**
 * A `Name` or `Identifier` that identifies the entity
 */
export type CrmP1IsIdentifiedBy = (CrmE33_E41_Linguistic_Appellation | CrmE42_Identifier)[];
/**
 * A `Type` which classifies this entity beyond the class given in the `type` property
 */
export type CrmP2HasType = CrmE55_Type[];
/**
 * A reference to one or more other identities for this entity, such as in external vocabularies or systems
 */
export type General16 = NoName[];
/**
 * The class of the entity
 */
export type RdfType4 = string;
/**
 * List of concept entities
 */
export type Specific14 = CrmE55_TypeOrSubclass[];
/**
 * The class of the entity
 */
export type RdfType5 = string;
export type Specific15 = "VisualItem";
/**
 * The class of the entity
 */
export type RdfType6 = string;
export type Specific16 = "DigitalObject";
/**
 * A URL from which the digital object is able to be retrieved
 */
export type LaAccessPoint = DigD1_Digital_ObjectSeeSchemaDigitalHtml[];
/**
 * The class of the entity
 */
export type RdfType7 = string;
/**
 * A standard or specification that this entity conforms to or embodies
 */
export type DctermsConformsTo = CrmE73_Information_Object[];
/**
 * A digital object that shows the current visual item
 */
export type LaDigitallyShownBy = DigD1_Digital_Object[];
/**
 * An embedded link through a VisualItem to a Digital Object
 */
export type CrmP138IHasRepresentation = CrmE36_Visual_Item[];
/**
 * A reference to one or more `Set` entities of which this entity is a member
 */
export type LaMemberOf = LaSet[];
/**
 * The class of the entity
 */
export type RdfType8 = string;
export type Specific17 = "LinguisticObject";
/**
 * A digital object that carries the current linguistic object
 */
export type LaDigitallyCarriedBy = DigD1_Digital_Object[];
/**
 * One or more human-readable web pages or other digital objects where the focus of the content is this entity
 */
export type CrmP129IIsSubjectOf = CrmE33_Linguistic_Object2[];
/**
 * One or more AttributeAssignments that relate some other entity to this one
 */
export type CrmP140IWasAttributedBy = CrmE13_Attribute_Assignment[];
/**
 * The class of the entity
 */
export type RdfType9 = string;
export type Specific18 = "Creation";
/**
 * An identified event or activity which this creation is part of
 */
export type CrmP9IFormsPartOf = CrmE6_Event | CrmE7_Activity;
/**
 * This concept is contained within one or more larger/broader concept entities
 */
export type SkosBroader = CrmE55_TypeOrSubclass[];
/**
 * The class of the entity
 */
export type RdfType10 = string;
export type Specific19 = "DigitalObject";
/**
 * A reference to one or more other identities for this entity, such as in external vocabularies or systems
 */
export type General17 = NoName[];
/**
 * List of equivalent `DigitalObject` entities
 */
export type Specific20 = DigD1_Digital_ObjectSeeSchemaDigitalHtml[];
/**
 * One or more `Dimension` structures that describe this entity
 */
export type CrmP43HasDimension = CrmE54_Dimension[];
/**
 * The class of the entity
 */
export type RdfType11 = string;
export type Specific21 = "DigitalService";
/**
 * A digital service that may be interacted with in order to retrieve or act upon the digital object
 */
export type LaDigitallyAvailableVia = LaDigitalService[];
export type LaDigitallyCarries = CrmE33_Linguistic_Object1[];
/**
 * The class of the entity
 */
export type RdfType12 = string;
export type LaDigitallyShows = CrmE36_Visual_Item1[];
/**
 * The class of the entity
 */
export type RdfType13 = string;
export type Specific22 = "Activity";
export type CrmP16IWasUsedFor = CrmE7_Activity1[];
/**
 * The class of the entity
 */
export type RdfType14 = string;
export type Specific23 = "Period" | "Event" | "Activity";
/**
 * A reference to one or more other identities for this entity, such as in external vocabularies or systems
 */
export type General18 = NoName[];
/**
 * List of equivalent `Activity` entities
 */
export type Specific24 = CrmE7_Activity[];
/**
 * An identified event or activity which this one is part of
 */
export type CrmP9IFormsPartOf1 = CrmE6_Event | CrmE7_Activity;
/**
 * The class of the entity
 */
export type RdfType15 = string;
export type Specific25 = "Group";
/**
 * A reference to one or more other identities for this entity, such as in external vocabularies or systems
 */
export type General19 = NoName[];
/**
 * List of `Group` entities
 */
export type Specific26 = CrmE74_Group[];
/**
 * A reference to one or more `Group` entities of which this entity is a member
 */
export type CrmP107IIsCurrentOrFormerMemberOf = CrmE74_Group[];
/**
 * One or more activities which this entity carried out or performed
 */
export type CrmP14IPerformed = CrmE7_Activity1[];
/**
 * An identifier which can be used as a contact point or address for the entity, such as an email address
 */
export type CrmP76HasContactPoint = CrmE42_Identifier[];
/**
 * A `Place` where this entity has resided or done business
 */
export type CrmP74HasCurrentOrFormerResidence = CrmE53_Place[];
/**
 * The class of the entity
 */
export type RdfType16 = string;
export type Specific27 = "Formation";
/**
 * An identified event or activity which this formation is part of
 */
export type CrmP9IFormsPartOf2 = CrmE6_Event | CrmE7_Activity;
/**
 * The class of the entity
 */
export type RdfType17 = string;
export type Specific28 = "Dissolution";
/**
 * An identified event or activity which this dissolution is part of
 */
export type CrmP9IFormsPartOf3 = CrmE6_Event | CrmE7_Activity;
/**
 * The class of the entity
 */
export type RdfType18 = string;
export type Specific29 = "VisualItem";
/**
 * A reference to one or more other identities for this entity, such as in external vocabularies or systems
 */
export type General20 = NoName[];
/**
 * List of equivalent `VisualItem` entities
 */
export type Specific30 = CrmE36_Visual_Item1[];
/**
 * The class of the entity
 */
export type RdfType19 = string;
export type Specific31 = "Right";
/**
 * One or more Rights that this object is subject to
 */
export type CrmP104IIsSubjectTo = CrmE30_Right[];
/**
 * Reference to another Visual Item or Linguistic Object of which this is part
 */
export type CrmP106IFormsPartOf = (CrmE36_Visual_Item1 | CrmE33_Linguistic_Object1)[];
/**
 * The main topic(s) of the content
 */
export type CrmP129IsAbout = NoName[];
/**
 * An entity which is represented in this image content
 */
export type CrmP138Represents = NoName[];
/**
 * A Type of an entity, which is represented in this image content
 */
export type LaRepresentsInstanceOfType = CrmE55_Type[];
export type CrmP16IWasUsedFor1 = CrmE7_Activity1[];
/**
 * The class of the entity
 */
export type RdfType20 = string;
export type Specific32 = "HumanMadeObject";
/**
 * A reference to one or more other identities for this entity, such as in external vocabularies or systems
 */
export type General21 = NoName[];
/**
 * List of `HumanMadeObject` entities
 */
export type Specific33 = CrmE22_HumanMade_Object[];
/**
 * The class of the entity
 */
export type RdfType21 = string;
/**
 * One or more `Material` types of which this object is made
 */
export type CrmP45ConsistsOf = CrmE57_Material[];
/**
 * The current owner (a `Person` or `Group`) of this object
 */
export type CrmP52HasCurrentOwner = (E21_Person | CrmE74_Group)[];
/**
 * The current custodian (a `Person` or `Group`) of this object, if different from its owner
 */
export type CrmP50HasCurrentKeeper = (E21_Person | CrmE74_Group)[];
/**
 * The current normal custodian (a `Person` or `Group`) if different from the current custodian, for example an object that is owned by an individual, currently in an exhibition, and normally under the custody of an organization
 */
export type LaCurrentPermanentCustodian = (E21_Person | CrmE74_Group)[];
/**
 * Activities that this entity was used for.
 */
export type CrmP16IWasUsedFor2 = CrmE7_Activity1[];
/**
 * A reference to a `VisualItem` that this object shows the image content of
 */
export type CrmP65ShowsVisualItem = CrmE36_Visual_Item1[];
/**
 * A reference to a `LinguisticObject` that this object carries the textual content of
 */
export type CrmP128Carries = CrmE33_Linguistic_Object1[];
/**
 * The class of the entity
 */
export type RdfType22 = string;
export type Specific34 = "Production";
/**
 * An identified event or activity which this activity is part of
 */
export type CrmP9IFormsPartOf4 = CrmE6_Event | CrmE7_Activity;
export type CrmP46IsComposedOf = CrmE12_Production[];
/**
 * The class of the entity
 */
export type RdfType23 = string;
export type Specific35 = "Destruction";
/**
 * An identified event or activity which this event is part of
 */
export type CrmP9IFormsPartOf5 = CrmE6_Event | CrmE7_Activity;
/**
 * The class of the entity
 */
export type RdfType24 = string;
export type Specific36 = "PartRemoval";
/**
 * An identified event or activity which this activity is part of
 */
export type CrmP9IFormsPartOf6 = CrmE6_Event | CrmE7_Activity;
/**
 * One or more `PartRemoval` activities in which this object was removed from another object
 */
export type CrmP113IWasRemovedBy = CrmE80_Part_Removal[];
/**
 * The class of the entity
 */
export type RdfType25 = string;
export type Specific37 = "Encounter";
/**
 * An identified event or activity which this activity is part of
 */
export type CrmP9IFormsPartOf7 = CrmE6_Event | CrmE7_Activity;
/**
 * One or more Encounter activities in which this object was encountered
 */
export type SciO19IWasObjectEncounteredAt = SciS19_Encounter_Event[];
/**
 * The class of the entity
 */
export type RdfType26 = string;
export type Specific38 = "Person";
/**
 * A reference to one or more other identities for this entity, such as in external vocabularies or systems
 */
export type General22 = NoName[];
/**
 * List of `Person` entities
 */
export type Specific39 = E21_Person[];
/**
 * The class of the entity
 */
export type RdfType27 = string;
export type Specific40 = "Birth";
/**
 * The class of the entity
 */
export type RdfType28 = string;
export type Specific41 = "Death";
/**
 * The class of the entity
 */
export type RdfType29 = string;
export type Specific42 = "Place";
/**
 * A reference to one or more other identities for this entity, such as in external vocabularies or systems
 */
export type General23 = NoName[];
/**
 * List of `Place` entities
 */
export type Specific43 = CrmE53_Place[];
/**
 * A string with a WKT or GeoJSON definition of the area of the Place
 */
export type CrmP168PlaceIsDefinedBy = string;
/**
 * This `Place` is contained within one or more larger `Place` entities
 */
export type CrmP89FallsWithin = CrmE53_Place[];
/**
 * The class of the entity
 */
export type RdfType30 = string;
export type Specific44 = "Activity";
/**
 * A reference to one or more other identities for this entity, such as in external vocabularies or systems
 */
export type General24 = NoName[];
/**
 * List of equivalent `Activity` entities
 */
export type Specific45 = CrmE7_Activity[];
/**
 * An identified event or activity which this activity is part of
 */
export type CrmP9IFormsPartOf8 = CrmE6_Event | CrmE7_Activity;
/**
 * The class of the entity
 */
export type RdfType31 = string;
export type Specific46 = "Acquisition";
export type CrmP23TransferredTitleFrom = (E21_Person | CrmE74_Group)[];
export type CrmP22TransferredTitleTo = (E21_Person | CrmE74_Group)[];
export type CrmP24TransferredTitleOf = CrmE22_HumanMade_Object[];
/**
 * The class of the entity
 */
export type RdfType32 = string;
export type Specific47 = "RightAcquisition";
export type LaEstablishes = CrmE30_Right[];
export type LaInvalidates = CrmE30_Right[];
/**
 * The class of the entity
 */
export type RdfType33 = string;
export type Specific48 = "TransferOfCustody";
export type CrmP28CustodySurrenderedBy = (E21_Person | CrmE74_Group)[];
export type CrmP29CustodyReceivedBy = (E21_Person | CrmE74_Group)[];
export type CrmP30TransferredCustodyOf = CrmE22_HumanMade_Object[];
/**
 * The class of the entity
 */
export type RdfType34 = string;
export type Specific49 = "Payment";
export type LaPaidFrom = (E21_Person | CrmE74_Group)[];
export type LaPaidTo = (E21_Person | CrmE74_Group)[];
/**
 * The class of the entity
 */
export type RdfType35 = string;
export type Specific50 = "MonetaryAmount";
/**
 * The class of the entity
 */
export type RdfType36 = string;
/**
 * The class of the entity
 */
export type RdfType37 = string;
export type Specific51 = "Encounter";
/**
 * The objects that were encountered during this event
 */
export type SciO19HasFoundObject = CrmE22_HumanMade_Object[];
/**
 * The class of the entity
 */
export type RdfType38 = string;
export type Specific52 = "Move";
/**
 * The objects that were moved
 */
export type CrmP25Moved = CrmE22_HumanMade_Object[];
/**
 * The class of the entity
 */
export type RdfType39 = string;
export type Specific53 = "Activity";
/**
 * More specific parts of the event
 */
export type CrmP9ConsistsOf = (
  | CrmE8_Acquisition
  | LaRightAcquisition
  | CrmE10_TransferOf_Custody
  | LaPayment
  | SciS19_Encounter_Event1
  | CrmE9_Move
  | CrmE7_Activity2
)[];
/**
 * The class of the entity
 */
export type RdfType40 = string;
export type Specific54 = "Set";
/**
 * A reference to one or more other identities for this entity, such as in external vocabularies or systems
 */
export type General25 = NoName[];
/**
 * List of equivalent `Set` entities
 */
export type Specific55 = LaSet[];
export type CrmP16IWasUsedFor3 = CrmE7_Activity1[];
/**
 * The class of the entity
 */
export type RdfType41 = string;
export type Specific56 = "LinguisticObject";
/**
 * A reference to one or more other identities for this entity, such as in external vocabularies or systems
 */
export type General26 = NoName[];
/**
 * List of equivalent `LinguisticObject` entities
 */
export type Specific57 = CrmE33_Linguistic_Object1[];
export type CrmP16IWasUsedFor4 = CrmE7_Activity1[];
/**
 * Reference to another Linguistic Object or Visual Item of which this is part
 */
export type CrmP106IFormsPartOf1 = (CrmE36_Visual_Item1 | CrmE33_Linguistic_Object1)[];

/**
 * _crm:E55\_Type_
 * Concepts, Subjects and other categorizations.
 * See: [API](https://linked.art/api/1.0/endpoint/place/) | [Model](https://linked.art/model/)
 */
export interface ConceptSchema {
  "@context": JSONLDContext;
  id: TheSubjectUri;
  type: General & Specific;
  _label: RdfsLabel;
  classified_as?: CrmP2HasType;
  identified_by?: CrmP1IsIdentifiedBy;
  referred_to_by?: CrmP67IIsReferredToBy;
  equivalent?: General16 & Specific14;
  representation?: CrmP138IHasRepresentation;
  member_of?: LaMemberOf;
  subject_of?: CrmP129IIsSubjectOf;
  attributed_by?: CrmP140IWasAttributedBy;
  created_by?: CrmP94IWasCreatedBy;
  broader?: SkosBroader;
}
/**
 * A concept or 'Type' in the taxonomic sense
 * See: [API](https://linked.art/api/1.0/shared/type/) | [Model](https://linked.art/model/base/#types-and-classifications)
 */
export interface CrmE55_Type {
  id: TheSubjectUri;
  _label?: RdfsLabel;
  type: General1 & Specific1;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
}
/**
 * A name of an entity
 * See: [API](https://linked.art/api/1.0/shared/name/) | [Model](https://linked.art/model/base/#names)
 */
export interface CrmE33_E41_Linguistic_Appellation {
  _label?: RdfsLabel;
  type: General2 & Specific2;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  content: CrmP190HasSymbolicContent;
  language?: CrmP72HasLanguage;
  referred_to_by?: CrmP67IIsReferredToBy;
  /**
   * A list of one or more `Name` structures, which are parts of this `Name`
   */
  part?: CrmE33_E41_Linguistic_Appellation[];
}
/**
 * Reference to a `Language`
 */
export interface CrmE56_Language {
  id: TheSubjectUri;
  type: General3 & "Language";
  _label?: RdfsLabel;
}
/**
 * An embedded, relatively short piece of textual content
 * See: [API](https://linked.art/api/1.0/shared/statement/) | [Model](https://linked.art/model/base/#statements-about-a-resource)
 */
export interface CrmE33_Linguistic_Object {
  _label?: RdfsLabel;
  type: General4 & Specific3;
  identified_by?: CrmP1IsIdentifiedBy;
  referred_to_by?: CrmP67IIsReferredToBy;
  classified_as?: CrmP2HasType;
  content: CrmP190HasSymbolicContent;
  language?: CrmP72HasLanguage;
  format?: DcFormat;
}
/**
 * Reference to a `DigitalObject`
 */
export interface DigD1_Digital_ObjectSeeSchemaDigitalHtml {
  id: TheSubjectUri;
  type: General5 & Specific4;
  _label?: RdfsLabel;
}
/**
 * Reference to a `LinguisticObject`
 * See: [Schema](text.html)
 */
export interface CrmE33_Linguistic_Object1 {
  id: TheSubjectUri;
  type: General6 & "LinguisticObject";
  _label?: RdfsLabel;
}
/**
 * An identifier for an entity
 * See: [API](https://linked.art/api/1.0/shared/identifier/) | [Model](https://linked.art/model/base/#identifiers)
 */
export interface CrmE42_Identifier {
  _label?: RdfsLabel;
  type: General7 & Specific5;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  content: CrmP190HasSymbolicContent;
  /**
   * A list of one or more `Identifier` structures, which are parts of this `Identifier`
   */
  part?: CrmE42_Identifier[];
  /**
   * The activity through which this `Identifier` was assigned to the entity
   */
  assigned_by?: CrmE13_Attribute_Assignment[];
}
/**
 * An activity which involves the assignment of some value to some entity, often with an explicit relationship between value and entity
 */
export interface CrmE13_Attribute_Assignment {
  type: General8 & Specific6;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  part_of?: CrmE6_Event | CrmE7_Activity;
  assigned?: NoName1;
  assigned_property?: CrmP177AssignedPropertyType;
}
/**
 * Reference to a `Place` entity
 * See: [Schema](place.html)
 */
export interface CrmE53_Place {
  id: TheSubjectUri;
  type: General9 & Specific7;
  _label?: RdfsLabel;
}
/**
 * A `TimeSpan` which describes the date-time range during which this event occured
 */
export interface CrmP4HasTimeSpan {
  _label?: RdfsLabel;
  type: General10 & Specific8;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  begin_of_the_begin?: CrmP82ABeginOfTheBegin;
  end_of_the_begin?: CrmP81AEndOfTheBegin;
  begin_of_the_end?: CrmP81BBeginOfTheEnd;
  end_of_the_end?: CrmP82BEndOfTheEnd;
  duration?: CrmP191HadDuration;
}
/**
 * A `Dimension` that describes the duration of the timespan within any given date-times
 */
export interface CrmP191HadDuration {
  _label?: RdfsLabel;
  type: General11 & Specific9;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  value: CrmP90HasValue;
  lower_value_limit?: CrmP90AHasLowerValueLimit;
  upper_value_limit?: CrmP90AHasUpperValueLimit;
  unit: CrmP91HasUnit;
  assigned_by?: CrmP141IWasAssignedBy;
}
/**
 * Reference to the MeasurementUnit for this dimension
 */
export interface CrmP91HasUnit {
  id: TheSubjectUri;
  type: General12 & "MeasurementUnit";
  _label?: RdfsLabel;
}
/**
 * Reference to an `Event`
 * See: [Schema](event.html)
 */
export interface CrmE6_Event {
  id: TheSubjectUri;
  type: General13 & "Event";
  _label?: RdfsLabel;
}
/**
 * Reference to an `Activity`
 * See: [Schema](event.html)
 */
export interface CrmE7_Activity {
  id: TheSubjectUri;
  type: General14 & "Activity";
  _label?: RdfsLabel;
}
/**
 * Reference to a `Person`
 * See: [Schema](person.html)
 */
export interface E21_Person {
  id: TheSubjectUri;
  type: General15 & Specific10;
  _label?: RdfsLabel;
}
/**
 * Reference to a `Group`
 * See: [Schema](group.html)
 */
export interface CrmE74_Group {
  id: TheSubjectUri;
  type: RdfType & Specific11;
  _label?: RdfsLabel;
}
/**
 * Reference to a `HumanMadeObject`
 * See: [Schema](object.html)
 */
export interface CrmE22_HumanMade_Object {
  id: TheSubjectUri;
  type: RdfType1 & Specific12;
  _label?: RdfsLabel;
}
/**
 * Reference to a `Set`
 * See: [Schema](set.html)
 */
export interface LaSet {
  id: TheSubjectUri;
  type: RdfType2 & "Set";
  _label?: RdfsLabel;
}
/**
 * Reference to another primary entity
 * See: [API](https://linked.art/api/1.0/shared/reference/) | [Model]()
 */
export interface NoName {
  id: TheSubjectUri;
  type: RdfType3 & Specific13;
  _label?: RdfsLabel;
}
/**
 * Attribute Assignments can assign any entity, structure or value
 */
export interface NoName1 {
  [k: string]: unknown;
}
/**
 * Reference to a Type or any subclass (Language, Material, Currency, MeasurementUnit)
 */
export interface CrmE55_TypeOrSubclass {
  id: TheSubjectUri;
  type: RdfType4 & ("Type" | "Language" | "Material" | "Currency" | "MeasurementUnit");
  _label?: RdfsLabel;
}
/**
 * An embedded Visual Item, such as the content of a digital image
 */
export interface CrmE36_Visual_Item {
  type: RdfType5 & Specific15;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  digitally_shown_by?: LaDigitallyShownBy;
}
/**
 * An embedded Digital Object, such as a home page reference
 */
export interface DigD1_Digital_Object {
  type?: RdfType6 & Specific16;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  access_point?: LaAccessPoint;
  format?: DcFormat;
  conforms_to?: DctermsConformsTo;
  [k: string]: unknown;
}
/**
 * Reference to an `InformationObject`
 */
export interface CrmE73_Information_Object {
  id: TheSubjectUri;
  type: RdfType7 & "InformationObject";
  _label?: RdfsLabel;
}
/**
 * An embedded Linguistic Object, such as the content of a web page
 */
export interface CrmE33_Linguistic_Object2 {
  type: RdfType8 & Specific17;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  language?: CrmP72HasLanguage;
  digitally_carried_by?: LaDigitallyCarriedBy;
}
/**
 * The creation of the intellectual/conceptual entity
 */
export interface CrmP94IWasCreatedBy {
  type?: RdfType9 & Specific18;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  part_of?: CrmP9IFormsPartOf;
  [k: string]: unknown;
}
/**
 * _dig:D1\_Digital\_Object_
 * A digital resource, such as a web page or image.
 * See: [API](https://linked.art/api/1.0/endpoint/digital_object/) | [Model](https://linked.art/model/digital/)
 */
export interface DigitalObjectSchema {
  "@context": JSONLDContext;
  id: TheSubjectUri;
  type: RdfType10 & Specific19;
  _label: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  equivalent?: General17 & Specific20;
  representation?: CrmP138IHasRepresentation;
  member_of?: LaMemberOf;
  subject_of?: CrmP129IIsSubjectOf;
  attributed_by?: CrmP140IWasAttributedBy;
  dimension?: CrmP43HasDimension;
  part_of?: DigD1_Digital_ObjectSeeSchemaDigitalHtml1;
  format?: DcFormat;
  conforms_to?: DctermsConformsTo;
  access_point?: LaAccessPoint;
  digitally_available_via?: LaDigitallyAvailableVia;
  digitally_carries?: LaDigitallyCarries;
  digitally_shows?: LaDigitallyShows;
  used_for?: CrmP16IWasUsedFor;
  created_by?: CrmP94IWasCreatedBy1;
}
/**
 * A measurable aspect of an entity, with a numeric value, a unit for that value, and a type relative to the entity
 * See: [API](https://linked.art/api/1.0/shared/dimension/) | [Model](https://linked.art/model/object/physical/#dimensions)
 */
export interface CrmE54_Dimension {
  _label?: RdfsLabel;
  type: General11 & Specific9;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  value: CrmP90HasValue;
  lower_value_limit?: CrmP90AHasLowerValueLimit;
  upper_value_limit?: CrmP90AHasUpperValueLimit;
  unit: CrmP91HasUnit;
  assigned_by?: CrmP141IWasAssignedBy;
}
/**
 * Reference to a `DigitalObject`
 */
export interface DigD1_Digital_ObjectSeeSchemaDigitalHtml1 {
  id: TheSubjectUri;
  type: General5 & Specific4;
  _label?: RdfsLabel;
}
export interface LaDigitalService {
  type?: RdfType11 & Specific21;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  access_point?: LaAccessPoint;
  conforms_to?: DctermsConformsTo;
  [k: string]: unknown;
}
/**
 * Reference to a `VisualItem`
 * See: [Schema](image.html)
 */
export interface CrmE36_Visual_Item1 {
  id: TheSubjectUri;
  type: RdfType12 & "VisualItem";
  _label?: RdfsLabel;
}
/**
 * An activity carried out by some person or group
 */
export interface CrmE7_Activity1 {
  type: RdfType13 & Specific22;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  part_of?: CrmE6_Event | CrmE7_Activity;
}
/**
 * The creation of the intellectual/conceptual entity
 */
export interface CrmP94IWasCreatedBy1 {
  type?: RdfType9 & Specific18;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  part_of?: CrmP9IFormsPartOf;
  [k: string]: unknown;
}
/**
 * _crm:E4\_Period_, _crm:E6\_Event_ or _crm:E7\_Activity_
 * A period (a span of time at a place), event (a change that no one carried out) or activity (some human actor was responsible for it) that occured.
 * See: [API](https://linked.art/api/1.0/endpoint/event/) | [Model]()
 */
export interface EventSchema {
  "@context": JSONLDContext;
  id: TheSubjectUri;
  type: RdfType14 & Specific23;
  _label: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  equivalent?: General18 & Specific24;
  representation?: CrmP138IHasRepresentation;
  member_of?: LaMemberOf;
  subject_of?: CrmP129IIsSubjectOf;
  attributed_by?: CrmP140IWasAttributedBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  part_of?: CrmP9IFormsPartOf1;
}
/**
 * _crm:E74\_Group_
 * A Group of People and/or other Groups.
 * See: [API](https://linked.art/api/1.0/endpoint/group/) | [Model](https://linked.art/model/actor/)
 */
export interface GroupSchema {
  "@context": JSONLDContext;
  id: TheSubjectUri;
  type: RdfType15 & Specific25;
  _label: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  equivalent?: General19 & Specific26;
  representation?: CrmP138IHasRepresentation;
  member_of?: CrmP107IIsCurrentOrFormerMemberOf;
  subject_of?: CrmP129IIsSubjectOf;
  attributed_by?: CrmP140IWasAttributedBy;
  carried_out?: CrmP14IPerformed;
  contact_point?: CrmP76HasContactPoint;
  residence?: CrmP74HasCurrentOrFormerResidence;
  formed_by?: CrmP95IWasFormedBy;
  dissolved_by?: CrmP99IWasDissolvedBy;
}
/**
 * The activity of forming or creating the Group
 */
export interface CrmP95IWasFormedBy {
  type?: RdfType16 & Specific27;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  part_of?: CrmP9IFormsPartOf2;
  [k: string]: unknown;
}
/**
 * The activity of dissolving or ending the Group
 */
export interface CrmP99IWasDissolvedBy {
  type?: RdfType17 & Specific28;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  influenced_by?: CrmP15WasInfluencedBy;
  part_of?: CrmP9IFormsPartOf3;
  [k: string]: unknown;
}
/**
 * _crm:E36\_Visual\_Item_
 * The visual content of a work.
 * See: [API](https://linked.art/api/1.0/endpoint/visual_work/) | [Model](https://linked.art/model/object/aboutness/#physical-object-and-visual-work)
 */
export interface VisualContentSchema {
  "@context": JSONLDContext;
  id: TheSubjectUri;
  type: RdfType18 & Specific29;
  _label: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  equivalent?: General20 & Specific30;
  member_of?: LaMemberOf;
  subject_of?: CrmP129IIsSubjectOf;
  attributed_by?: CrmP140IWasAttributedBy;
  dimension?: CrmP43HasDimension;
  subject_to?: CrmP104IIsSubjectTo;
  part_of?: CrmP106IFormsPartOf;
  about?: CrmP129IsAbout;
  created_by?: CrmP94IWasCreatedBy3;
  represents?: CrmP138Represents;
  represents_instance_of_type?: LaRepresentsInstanceOfType;
  used_for?: CrmP16IWasUsedFor1;
}
/**
 * A legal right that can be held by some party over some entity
 */
export interface CrmE30_Right {
  _label?: RdfsLabel;
  type: RdfType19 & Specific31;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  created_by?: CrmP94IWasCreatedBy2;
  possessed_by?: (E21_Person | CrmE74_Group)[];
}
/**
 * The creation of the intellectual/conceptual entity
 */
export interface CrmP94IWasCreatedBy2 {
  type?: RdfType9 & Specific18;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  part_of?: CrmP9IFormsPartOf;
  [k: string]: unknown;
}
/**
 * The creation of the intellectual/conceptual entity
 */
export interface CrmP94IWasCreatedBy3 {
  type?: RdfType9 & Specific18;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  part_of?: CrmP9IFormsPartOf;
  [k: string]: unknown;
}
/**
 * _crm:E22\_Human-Made\_Object_
 * A human-made object, part thereof, or a natural object with value imbued through interaction with human culture.
 * See: [API](https://linked.art/api/1.0/endpoint/object/) | [Model](https://linked.art/model/object/)
 */
export interface HumanMadeObjectSchema {
  "@context": JSONLDContext;
  id: TheSubjectUri;
  type: RdfType20 & Specific32;
  _label: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  equivalent?: General21 & Specific33;
  representation?: CrmP138IHasRepresentation;
  member_of?: LaMemberOf;
  subject_of?: CrmP129IIsSubjectOf;
  attributed_by?: CrmP140IWasAttributedBy;
  dimension?: CrmP43HasDimension;
  made_of?: CrmP45ConsistsOf;
  part_of?: CrmE22_HumanMade_Object1;
  current_owner?: CrmP52HasCurrentOwner;
  current_custodian?: CrmP50HasCurrentKeeper;
  current_permanent_custodian?: LaCurrentPermanentCustodian;
  current_location?: CrmP55HasCurrentLocation;
  used_for?: CrmP16IWasUsedFor2;
  shows?: CrmP65ShowsVisualItem;
  carries?: CrmP128Carries;
  produced_by?: CrmP108IWasProducedBy;
  destroyed_by?: CrmP13IWasDestroyedBy;
  removed_by?: CrmP113IWasRemovedBy;
  encountered_by?: SciO19IWasObjectEncounteredAt;
}
/**
 * Reference to a `Material`
 */
export interface CrmE57_Material {
  id: TheSubjectUri;
  type: RdfType21 & "Material";
  _label?: RdfsLabel;
}
/**
 * Reference to a `HumanMadeObject`
 * See: [Schema](object.html)
 */
export interface CrmE22_HumanMade_Object1 {
  id: TheSubjectUri;
  type: RdfType1 & Specific12;
  _label?: RdfsLabel;
}
/**
 * The current location (a `Place`) of this object
 */
export interface CrmP55HasCurrentLocation {
  id: TheSubjectUri;
  type: General9 & Specific7;
  _label?: RdfsLabel;
}
/**
 * The `Production` activity which created this object
 */
export interface CrmP108IWasProducedBy {
  type?: RdfType22 & Specific34;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  part_of?: CrmP9IFormsPartOf4;
  part?: CrmP46IsComposedOf;
  [k: string]: unknown;
}
/**
 * The production/creation of the object
 */
export interface CrmE12_Production {
  type?: RdfType22 & Specific34;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  part_of?: CrmP9IFormsPartOf4;
  part?: CrmP46IsComposedOf;
  [k: string]: unknown;
}
/**
 * The `Destruction` event in which this object was destroyed
 */
export interface CrmP13IWasDestroyedBy {
  type?: RdfType23 & Specific35;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  part_of?: CrmP9IFormsPartOf5;
  [k: string]: unknown;
}
/**
 * The activity of removing this object from some other object.
 */
export interface CrmE80_Part_Removal {
  type?: RdfType24 & Specific36;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  part_of?: CrmP9IFormsPartOf6;
  diminished?: CrmE22_HumanMade_Object2;
  [k: string]: unknown;
}
/**
 * Reference to a `HumanMadeObject`
 * See: [Schema](object.html)
 */
export interface CrmE22_HumanMade_Object2 {
  id: TheSubjectUri;
  type: RdfType1 & Specific12;
  _label?: RdfsLabel;
}
/**
 * The activity during which this object was encountered, found or discovered.
 */
export interface SciS19_Encounter_Event {
  type?: RdfType25 & Specific37;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  part_of?: CrmP9IFormsPartOf7;
  [k: string]: unknown;
}
/**
 * _crm:E21\_Person_
 * A human.
 * See: [API](https://linked.art/api/1.0/endpoint/person/) | [Model](https://linked.art/model/actor/)
 */
export interface Person {
  "@context": JSONLDContext;
  id: TheSubjectUri;
  type: RdfType26 & Specific38;
  _label: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  equivalent?: General22 & Specific39;
  representation?: CrmP138IHasRepresentation;
  member_of?: CrmP107IIsCurrentOrFormerMemberOf;
  subject_of?: CrmP129IIsSubjectOf;
  attributed_by?: CrmP140IWasAttributedBy;
  carried_out?: CrmP14IPerformed;
  contact_point?: CrmP76HasContactPoint;
  residence?: CrmP74HasCurrentOrFormerResidence;
  born?: CrmP98IWasBorn;
  died?: CrmP100IDiedIn;
}
/**
 * The event in which this Person was born
 */
export interface CrmP98IWasBorn {
  type?: RdfType27 & Specific40;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  [k: string]: unknown;
}
/**
 * The event in which this Person died
 */
export interface CrmP100IDiedIn {
  type?: RdfType28 & Specific41;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  [k: string]: unknown;
}
/**
 * _crm:E53\_Place_
 * Geographic locations where activities occur.
 * See: [API](https://linked.art/api/1.0/endpoint/place/) | [Model](https://linked.art/model/place/)
 */
export interface PlaceSchema {
  "@context": JSONLDContext;
  id: TheSubjectUri;
  type: RdfType29 & Specific42;
  _label: RdfsLabel;
  classified_as?: CrmP2HasType;
  identified_by?: CrmP1IsIdentifiedBy;
  referred_to_by?: CrmP67IIsReferredToBy;
  equivalent?: General23 & Specific43;
  representation?: CrmP138IHasRepresentation;
  member_of?: LaMemberOf;
  subject_of?: CrmP129IIsSubjectOf;
  attributed_by?: CrmP140IWasAttributedBy;
  defined_by?: CrmP168PlaceIsDefinedBy;
  part_of?: CrmP89FallsWithin;
}
/**
 * _crm:E7\_Activity_
 * A broad activity during which the ownership, custody, location or other rights related to one or more objects are changed
 * See: [API](https://linked.art/api/1.0/endpoint/provenance/) | [Model](https://linked.art/model/provenance/)
 */
export interface ProvenanceActivitySchema {
  "@context": JSONLDContext;
  id: TheSubjectUri;
  type: RdfType30 & Specific44;
  _label: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  equivalent?: General24 & Specific45;
  representation?: CrmP138IHasRepresentation;
  member_of?: LaMemberOf;
  subject_of?: CrmP129IIsSubjectOf;
  attributed_by?: CrmP140IWasAttributedBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  part_of?: CrmP9IFormsPartOf8;
  part?: CrmP9ConsistsOf;
}
/**
 * The transfer of ownership of a physical object between parties
 */
export interface CrmE8_Acquisition {
  type: RdfType31 & Specific46;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  transferred_title_from?: CrmP23TransferredTitleFrom;
  transferred_title_to?: CrmP22TransferredTitleTo;
  transferred_title_of: CrmP24TransferredTitleOf;
}
export interface LaRightAcquisition {
  type: RdfType32 & Specific47;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  establishes: LaEstablishes;
  invalidates?: LaInvalidates;
}
export interface CrmE10_TransferOf_Custody {
  type: RdfType33 & Specific48;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  transferred_custody_from?: CrmP28CustodySurrenderedBy;
  transferred_custody_to?: CrmP29CustodyReceivedBy;
  transferred_custody_of: CrmP30TransferredCustodyOf;
}
export interface LaPayment {
  type: RdfType34 & Specific49;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  paid_from?: LaPaidFrom;
  paid_to?: LaPaidTo;
  paid_amount?: LaPaidAmount;
}
export interface LaPaidAmount {
  _label?: RdfsLabel;
  type: RdfType35 & Specific50;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  value: CrmP90HasValue;
  lower_value_limit?: CrmP90AHasLowerValueLimit;
  upper_value_limit?: CrmP90AHasUpperValueLimit;
  currency: CrmE98_Currency;
}
/**
 * Reference to a `Currency`
 */
export interface CrmE98_Currency {
  id: TheSubjectUri;
  type: RdfType36 & "Currency";
  _label?: RdfsLabel;
}
export interface SciS19_Encounter_Event1 {
  type: RdfType37 & Specific51;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  encountered: SciO19HasFoundObject;
}
export interface CrmE9_Move {
  type: RdfType38 & Specific52;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  moved_from?: CrmE53_Place1;
  moved_to?: CrmE53_Place2;
  moved: CrmP25Moved;
}
/**
 * Reference to a `Place` entity
 * See: [Schema](place.html)
 */
export interface CrmE53_Place1 {
  id: TheSubjectUri;
  type: General9 & Specific7;
  _label?: RdfsLabel;
}
/**
 * Reference to a `Place` entity
 * See: [Schema](place.html)
 */
export interface CrmE53_Place2 {
  id: TheSubjectUri;
  type: General9 & Specific7;
  _label?: RdfsLabel;
}
export interface CrmE7_Activity2 {
  type: RdfType39 & Specific53;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
}
/**
 * _la:Set_
 * A collection of other resources, such as a set of objects or places.
 * [API](https://linked.art/api/1.0/endpoint/set/) | [Model](https://linked.art/model/collection/)
 */
export interface CollectionSchema {
  "@context": JSONLDContext;
  id: TheSubjectUri;
  type: RdfType40 & Specific54;
  _label: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  equivalent?: General25 & Specific55;
  representation?: CrmP138IHasRepresentation;
  member_of?: LaMemberOf;
  subject_of?: CrmP129IIsSubjectOf;
  attributed_by?: CrmP140IWasAttributedBy;
  dimension?: CrmP43HasDimension;
  about?: CrmP129IsAbout;
  /**
   * Great big bucket for arbitrary data here :(
   */
  members_exemplified_by?: unknown[];
  used_for?: CrmP16IWasUsedFor3;
  created_by?: CrmP94IWasCreatedBy4;
}
/**
 * The creation of the intellectual/conceptual entity
 */
export interface CrmP94IWasCreatedBy4 {
  type?: RdfType9 & Specific18;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  part_of?: CrmP9IFormsPartOf;
  [k: string]: unknown;
}
/**
 * _crm:E33\_Linguistic\_Object_
 * Textual content expressed in one or more human languages, which might or might not be written down on any physical carrier.
 * See: [API](https://linked.art/api/1.0/endpoint/textual_work/) | [Model](https://linked.art/model/document/)
 */
export interface TextSchema {
  "@context": JSONLDContext;
  id: TheSubjectUri;
  type: RdfType41 & Specific56;
  _label: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  equivalent?: General26 & Specific57;
  representation?: CrmP138IHasRepresentation;
  member_of?: LaMemberOf;
  subject_of?: CrmP129IIsSubjectOf;
  attributed_by?: CrmP140IWasAttributedBy;
  dimension?: CrmP43HasDimension;
  subject_to?: CrmP104IIsSubjectTo;
  format?: DcFormat;
  language?: CrmP72HasLanguage;
  about?: CrmP129IsAbout;
  created_by?: CrmP94IWasCreatedBy5;
  used_for?: CrmP16IWasUsedFor4;
  part_of?: CrmP106IFormsPartOf1;
  content?: CrmP190HasSymbolicContent;
}
/**
 * The creation of the intellectual/conceptual entity
 */
export interface CrmP94IWasCreatedBy5 {
  type?: RdfType9 & Specific18;
  _label?: RdfsLabel;
  identified_by?: CrmP1IsIdentifiedBy;
  classified_as?: CrmP2HasType;
  referred_to_by?: CrmP67IIsReferredToBy;
  took_place_at?: CrmP7TookPlaceAt;
  timespan?: CrmP4HasTimeSpan;
  caused_by?: SciO13IIsTriggeredBy;
  carried_out_by?: CrmP14CarriedOutBy;
  used_specific_object?: CrmP16UsedSpecificObject;
  influenced_by?: CrmP15WasInfluencedBy;
  technique?: CrmP32UsedGeneralTechnique;
  part_of?: CrmP9IFormsPartOf;
  [k: string]: unknown;
}
