// Generated by Xata Codegen 0.21.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "links",
    columns: [
      { name: "path", type: "string", unique: true },
      { name: "originalURL", type: "string", notNull: true, defaultValue: "" },
      { name: "qr", type: "text", notNull: true, defaultValue: "" },
      { name: "created", type: "datetime" },
      { name: "modified", type: "datetime" },
      { name: "views", type: "int", notNull: true, defaultValue: "0" },
      { name: "domain", type: "string", notNull: true, defaultValue: "" },
      { name: "title", type: "string" },
      { name: "tags", type: "multiple" },
      { name: "expiresAt", type: "datetime" },
      { name: "expiresURL", type: "string" },
      { name: "utmSource", type: "string" },
      { name: "utmMedium", type: "string" },
      { name: "utmCampaign", type: "string" },
      { name: "utmTerm", type: "string" },
      { name: "utmContent", type: "string" },
      { name: "redirectType", type: "int", notNull: true, defaultValue: "302" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Links = InferredTypes["links"];
export type LinksRecord = Links & XataRecord;

export type DatabaseSchema = {
  links: LinksRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://uib-ub-workspace-ta2cdc.eu-west-1.xata.sh/db/url-shortener",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
