/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react";

export const Index: Record<string, any> ={
  "iiif-image-demo": {
    name: "iiif-image-demo",
    description: "IIIF Image",
    type: "registry:example",
    files: [{
      path: "src/registry/default/examples/iiif-image-demo.tsx",
      content: "import { IIIFImage } from '../blocks/iiif-image/components';\n\nexport default function IIFImageDemo() {\n  return (\n    <div className='w-full h-96'>\n      <IIIFImage src='https://iiif.wellcomecollection.org/image/b29346423_0006.jp2/full/full/0/default.jpg' />\n    </div>\n  );\n}\n",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/default/examples/iiif-image-demo.tsx")),
    source: "import { IIIFImage } from '../blocks/iiif-image/components';\n\nexport default function IIFImageDemo() {\n  return (\n    <div className='w-full h-96'>\n      <IIIFImage src='https://iiif.wellcomecollection.org/image/b29346423_0006.jp2/full/full/0/default.jpg' />\n    </div>\n  );\n}\n",
  },
  "iiif-manifest-demo": {
    name: "iiif-manifest-demo",
    description: "IIIF Manifest",
    type: "registry:example",
    files: [{
      path: "src/registry/default/examples/iiif-manifest-demo.tsx",
      content: "import { IIIFManifest } from '../blocks/iiif-manifest/components';\n\nexport default function IIFManifestDemo() {\n  // Using a more reliable IIIF manifest for testing\n  const manifestUrl = 'https://api.ub.uib.no/items/ubb-bs-ok-00919?as=iiif';\n\n  return (\n    <div className=\"w-full h-full\">\n      <IIIFManifest iiifContent={manifestUrl} />\n    </div>\n  );\n}\n",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/default/examples/iiif-manifest-demo.tsx")),
    source: "import { IIIFManifest } from '../blocks/iiif-manifest/components';\n\nexport default function IIFManifestDemo() {\n  // Using a more reliable IIIF manifest for testing\n  const manifestUrl = 'https://api.ub.uib.no/items/ubb-bs-ok-00919?as=iiif';\n\n  return (\n    <div className=\"w-full h-full\">\n      <IIIFManifest iiifContent={manifestUrl} />\n    </div>\n  );\n}\n",
  },
  "iiif-image": {
    name: "iiif-image",
    description: "IIIF Image",
    type: "registry:block",
    files: [{
      path: "src/registry/default/blocks/iiif-image/components/index.tsx",
      content: "'use client';\n\nimport dynamic from 'next/dynamic';\n\nconst Image = dynamic(\n  () => import('@samvera/clover-iiif/image').then((Clover) => Clover.default),\n  {\n    ssr: false,\n  },\n);\n\nconst customTheme = {\n  showNavigator: false,\n  showHomeControl: false,\n  showControlPanel: false,\n  showZoomControl: false,\n  showFullPageControl: false,\n  showNavigationControl: false,\n  showRotationControl: false,\n};\n\nexport const IIIFImage = ({ src }: { src: string }) => {\n  return (\n    // eslint-disable-next-line jsx-a11y/alt-text\n    <Image\n      src={src}\n      openSeadragonConfig={customTheme}\n    />\n  );\n};\n",
      type: "registry:component",
    }],
  },
  "iiif-manifest": {
    name: "iiif-manifest",
    description: "IIIF Manifest",
    type: "registry:block",
    files: [{
      path: "src/registry/default/blocks/iiif-manifest/components/index.tsx",
      content: "'use client';\n\nimport dynamic from 'next/dynamic';\n\nconst Viewer = dynamic(\n  () => import('@samvera/clover-iiif/viewer').then((Clover) => Clover.default),\n  {\n    ssr: false,\n  },\n);\n\nconst customTheme = {\n  colors: {\n    /**\n     * Black and dark grays in a light theme.\n     * All must contrast to 4.5 or greater with \`secondary\`.\n     */\n    primary: \"var(--primary)\",\n    primaryMuted: \"var(--muted)\",\n    primaryAlt: \"var(--primary)\",\n\n    /**\n     * Key brand color(s).\n     * \`accent\` must contrast to 4.5 or greater with \`secondary\`.\n     */\n    accent: \"var(--color-core-500)\",\n    accentMuted: \"var(--color-core-400)\",\n    accentAlt: \"var(--color-core-600)\",\n\n    /**\n     * White and light grays in a light theme.\n     * All must must contrast to 4.5 or greater with \`primary\` and  \`accent\`.\n     */\n    secondary: \"var(--color-white)\",\n    secondaryMuted: \"var(--color-core-100)\",\n    secondaryAlt: \"var(--color-core-200)\",\n  },\n  fonts: {\n    sans: \"'Open Sans', sans-serif\",\n    display: \"Optima, Georgia, Arial, sans-serif\",\n  },\n};\n\nconst options = {\n  canvasHeight: 'auto',\n  showIIIFBadge: false,\n};\n\nexport const IIIFManifest = ({ iiifContent }: { iiifContent: string | Record<string, unknown> }) => {\n  return (\n    <div className='relative h-[70vh] w-full z-0'>\n      <Viewer\n        iiifContent={iiifContent}\n        customTheme={customTheme}\n        options={options}\n      />\n    </div>\n  );\n};",
      type: "registry:component",
    }],
  },
}