name: Manually publish container image using the last commit SHA as an image tag

on:
  pull_request: # run on pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Print the pr last commit SHA (shortened)
      if: ${{ github.event_name == 'pull_request' }}
      run: echo "The commit SHA is ${{ format('{0:.7}', github.event.pull_request.head.sha) }}"
